### ISSUE TITLE
OpenSSH auth attacks mitigation

### ISSUE THREAD

**Issue by devnexen** [HardenedBSD/hardenedBSD#101]
I found that today
http://gitweb.dragonflybsd.org/dragonfly.git/commit/a4ac8286be21b1495af8ec1db83271dacaa79556

The idea looks interesting, I would choose another approach though ... rather implementing the mitigation inside openssh directly rather than reading log files.

**Comment by opntr** [comment]
I like to keep the contrib software untouched. The idea is good, but not yet complete:
~~~
* See man page for details.  Still under construction (feel free to submit
  additional features).
~~~ dfly's commit.

If we import this functionality, than we keep this off be default.
If you like to implement this in OpenSSH site, you should contact with OpenBSD, and upstream the changes or implement in OpenBSD's side.

Other thing, that I note really like:
~~~
  The operator also typically sets up a cron job to clean out the IPFW rules
  that have accumulated once a day.
~~~

If this a standalone utility, than why not able to manage the cleanup too?

Btw, there exists a similar, but (from site) much powerful tool: http://sourceforge.net/projects/sshguard/ , which has BSD license too.

**Comment by opntr** [comment]
And there are more problems with the dfly's version:
http://gitweb.dragonflybsd.org/dragonfly.git/blob/a4ac8286be21b1495af8ec1db83271dacaa79556:/usr.sbin/sshlockout/sshlockout.c#l167

The rules are hardcoded (rule number, ssh-port, etc..) , and the ipfw command use relative path, not a full path.

**Comment by devnexen** [comment]
You raised good points mainly, although this dfly utility is only an early version.

**Comment by opntr** [comment]
And they should use ipfw tables, instead of new rule to every IP: https://forums.freebsd.org/threads/how-to-make-ipfw-table.5896/

**Comment by opntr** [comment]
Can we somehow add / CC dfly developers to github issue?

**Comment by devnexen** [comment]
Good idea.

**Comment by opntr** [comment]
whaaa, the sshguard has hardcoded ipfw ranges too...

**Comment by opntr** [comment]
wontfix - ENOTIME
