### ISSUE TITLE
unable to installworld/distribute HardenedBSD 11-CURRENT on FreeBSD 10-STABLE

### ISSUE THREAD

**Issue by opntr** [HardenedBSD/hardenedBSD#102]
I use this script:

install.sh:
~~~
#!/usr/bin/env csh

set DESTDIR="/target"
set SRC_DIR="${DESTDIR}/usr/src"
set MAKEOBJDIRPREFIX="${DESTDIR}/usr/obj"
set KERNCONF="OP-HBSD"
set T_start=`date`

if ( ! -e ${SRC_DIR}/.git ) then
        git clone https://github.com/HardenedBSD/hardenedbsd.git ${SRC_DIR}
endif

cd ${SRC_DIR}

make -j5 buildworld MAKEOBJDIRPREFIX=${MAKEOBJDIRPREFIX}
make -j5 kernel MAKEOBJDIRPREFIX=${MAKEOBJDIRPREFIX} KERNCONF=${KERNCONF}

make installworld DESTDIR=${DESTDIR} MAKEOBJDIRPREFIX=${MAKEOBJDIRPREFIX} && \
make distribution DESTDIR=${DESTDIR} MAKEOBJDIRPREFIX=${MAKEOBJDIRPREFIX}

cp /etc/make.conf /target/etc/
cp /etc/src.conf /target/etc/
cp /etc/rc.conf /target/etc/

set T_stop=`date`

echo ${T_start}
echo ${T_stop}
~~~

I got this error:

~~~
--------------------------------------------------------------
>>> Installing everything
--------------------------------------------------------------
cd /target/usr/src; make -f Makefile.inc1 install
===> share/info (install)
===> lib (install)
===> lib/csu/amd64 (install)
install -o root -g wheel -m 444  crt1.o crti.o crtn.o Scrt1.o gcrt1.o /target/usr/lib
===> lib/libc (install)
install -C -o root -g wheel -m 444   libc.a /target/usr/lib
install -C -o root -g wheel -m 444   libc_p.a /target/usr/lib
install: libc_p.a: No such file or directory
*** Error code 71

Stop.
make[5]: stopped in /target/usr/src/lib/libc
*** Error code 1

Stop.
make[4]: stopped in /target/usr/src/lib
*** Error code 1

Stop.
make[3]: stopped in /target/usr/src
*** Error code 1

Stop.
make[2]: stopped in /target/usr/src
*** Error code 1

Stop.
make[1]: stopped in /target/usr/src
*** Error code 1

Stop.
make: stopped in /target/usr/src
~~~

**Comment by opntr** [comment]
/etc/src.conf:
~~~
WITH_CLANG=
WITH_CLANG_EXTRAS=
WITH_CLANG_IS_CC=
WITH_IDEA=
WITH_LLDB=
WITHOUT_BLUETOOTH=
WITHOUT_CTM=
WITHOUT_FLOPPY=
WITHOUT_FREEBSD_UPDATE=
WITHOUT_IPX=
WITHOUT_NDIS=
WITHOUT_PC_SYSINSTALL=
WITHOUT_RCMDS=
WITHOUT_RCS=
WITHOUT_SETUID_LOGIN=
WITHOUT_SYSINSTALL=
WITHOUT_ZFS=

#XXX
WITH_PIE=
~~~

**Comment by schwer-q** [comment]
Hmmm... I take a look on the log and I found a few build error... 

--- cat_stub.c ---
echo "int _crunched_cat_stub(int argc, char **argv, char **envp){return main(argc,argv,envp);}" >cat_stub.c
make[5]: make[5]: don't know how to make /target/usr/obj/target/usr/src/rescue/rescue//target/usr/src/bin/cat/cat.o. Stop

make[5]: stopped in /target/usr/obj/target/usr/src/rescue/rescue
*** [rescue] Error code 2

make[4]: stopped in /target/usr/src/rescue/rescue
1 error

make[4]: stopped in /target/usr/src/rescue/rescue
*** [_sub.all] Error code 2

make[3]: stopped in /target/usr/src/rescue
1 error

make[3]: stopped in /target/usr/src/rescue
*** [rescue.all__D] Error code 2

make[2]: stopped in /target/usr/src
--- sys.all__D ---
A failure has been detected in another branch of the parallel make

make[5]: stopped in /target/usr/src/sys/boot/libstand32
*** [_sub.all] Error code 2

make[4]: stopped in /target/usr/src/sys/boot
1 error

make[4]: stopped in /target/usr/src/sys/boot
*** [_sub.all] Error code 2

make[3]: stopped in /target/usr/src/sys
1 error

make[3]: stopped in /target/usr/src/sys
*** [sys.all__D] Error code 2

make[2]: stopped in /target/usr/src
--- sbin.all__D ---
A failure has been detected in another branch of the parallel make

make[5]: stopped in /target/usr/src/sbin/ipf/libipf
*** [_sub.all] Error code 2

make[4]: stopped in /target/usr/src/sbin/ipf
1 error

make[4]: stopped in /target/usr/src/sbin/ipf
*** [all_subdir_ipf] Error code 2

make[3]: stopped in /target/usr/src/sbin
1 error

make[3]: stopped in /target/usr/src/sbin
*** [sbin.all__D] Error code 2

make[2]: stopped in /target/usr/src
--- secure.all__D ---
A failure has been detected in another branch of the parallel make

make[5]: stopped in /target/usr/src/secure/usr.sbin/sshd
*** [_sub.all] Error code 2

make[4]: stopped in /target/usr/src/secure/usr.sbin
1 error

make[4]: stopped in /target/usr/src/secure/usr.sbin
*** [_sub.all] Error code 2

make[3]: stopped in /target/usr/src/secure
1 error

make[3]: stopped in /target/usr/src/secure
*** [secure.all__D] Error code 2

make[2]: stopped in /target/usr/src
--- share.all__D ---
A failure has been detected in another branch of the parallel make

make[6]: stopped in /target/usr/src/share/doc/smm/01.setup
*** [_sub.all] Error code 2

make[5]: stopped in /target/usr/src/share/doc/smm
1 error

make[5]: stopped in /target/usr/src/share/doc/smm
*** [_sub.all] Error code 2

make[4]: stopped in /target/usr/src/share/doc
1 error

make[4]: stopped in /target/usr/src/share/doc
*** [_sub.all] Error code 2

make[3]: stopped in /target/usr/src/share
1 error

make[3]: stopped in /target/usr/src/share
*** [share.all__D] Error code 2

make[2]: stopped in /target/usr/src
5 errors

make[2]: stopped in /target/usr/src
*** [everything] Error code 2

make[1]: stopped in /target/usr/src
1 error

make[1]: stopped in /target/usr/src
*** [buildworld] Error code 2

make: stopped in /target/usr/src
1 error

make: stopped in /target/usr/src
--- buildkernel ---
--- buildkernel ---
ERROR: Missing kernel configuration file(s) (HARDENEDBSD).
*** [buildkernel] Error code 1

make[1]: stopped in /target/usr/src
1 error

make[1]: stopped in /target/usr/src
*** [buildkernel] Error code 2

make: stopped in /target/usr/src
1 error

**Comment by opntr** [comment]
the missing kernel config part are fine, under vanilla FreeBSD don't exists, but the crunchgen part are weird...

**Comment by opntr** [comment]
hohooo: https://lists.freebsd.org/pipermail/freebsd-bugs/2014-October/058502.html

**Comment by opntr** [comment]
and the workaround:

~~~
#!/usr/bin/env csh

set DESTDIR="/target"
set SRC_DIR="${DESTDIR}/usr/src"
set MAKEOBJDIRPREFIX="${DESTDIR}/usr/obj"
set KERNCONF="HARDENEDBSD"
set T_start=`date`

setenv __MAKE_CONF "/dev/null"
setenv __SRC_CONF "/target/src.conf"
setenv MAKE_CONF "/dev/null"
setenv SRC_CONF "/target/src.conf"

echo "src.conf:"
cat ${SRC_CONF}
echo

# broken MAKEOBJDIRPREFIX workaround
mount -t nullfs ${MAKEOBJDIRPREFIX} /usr/obj

set _nullfs=`mount | grep -c nullfs`
if ( ${_nullfs} != 1 ) then
        set _err=255
        goto err
endif

if ( ! -e ${SRC_DIR}/.git ) then
        git clone https://github.com/HardenedBSD/hardenedbsd.git ${SRC_DIR}
endif

cd ${SRC_DIR}

set _GIT_HEAD=`git branch | awk '/\*/{print $2}'`
if ( ${_GIT_HEAD} == "master" ) then
        set KERNCONF="GENERIC"
endif

make -j5 buildworld DESTDIR=${DESTDIR} || set _err=1 1 && goto err
make -j5 buildkernel DESTDIR=${DESTDIR} KERNCONF=${KERNCONF} || set _err=2 && goto err
make installkernel DESTDIR=${DESTDIR} KERNCONF=${KERNCONF} || set _err=3 && goto err
make installworld DESTDIR=${DESTDIR} || set _err=4 && goto err
make distribution DESTDIR=${DESTDIR} || set _err=5 && goto err

cp /etc/make.conf /target/etc/
cp /etc/src.conf /target/etc/
cp /etc/rc.conf /target/etc/

set T_stop=`date`

echo "start: ${T_start}"
echo "strop: ${T_stop}"

err:
        umount /usr/obj
        exit ${_err}
~~~

**Comment by opntr** [comment]
https://github.com/HardenedBSD/tools/blob/master/fuck-the-system.csh
