### ISSUE TITLE
release installers with HARDENEDBSD{,-IPSEC} kernels

### ISSUE THREAD

**Issue by opntr** [HardenedBSD/hardenedBSD#107]
Devin Teske: @Zer0Pntr Yes. "bsdinstall distextract" takes env DISTRIBUTIONS="base.txz doc.txz ... kernel.txz otherkernel.txz" BSDINSTALL_DISTDIR=/dir

**Comment by opntr** [comment]
We should write a bsdinstall plugin, which able:
* to choose the required kernel(s)
* update the DISTRIBUTIONS env var
* set the required default kernel in /boot/loader.conf

**Comment by lattera** [comment]
+1

I can take this if that's okay with you.

**Comment by opntr** [comment]
ok

**Comment by opntr** [comment]
IPSEC is already included in GENERIC kernel since middle of july

**Comment by opntr** [comment]
(already included in HARDENEDBSD and GENERIC kernel config)
