### ISSUE TITLE
Completely Remove freebsd-update From HardenedBSD

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#113]
I've had multiple people ask about using freebsd-update to update HardenedBSD. Since we don't have the infrastructure for it and since we'll likely write our own tool from scratch, should we remove freebsd-update from HardenedBSD?

**Comment by kibab** [comment]
I would say the project should provide its own infrastructure for that. Writing the separate tool to solve the already solved problem doesn't seem to be a good time investment. I think it should not be hard to ask FreeBSD people to give the advice on setting up FreeBSD-update server.

**Comment by kibab** [comment]
Actually there is an article on building the freebsd-update server, https://www.freebsd.org/doc/en_US.ISO8859-1/articles/freebsd-update-server/article.html

**Comment by opntr** [comment]
@kibab kibab: thanks for the link!

**Comment by opntr** [comment]
https://github.com/HardenedBSD/hardenedBSD/issues/120 - duplicated ticket - currently we just disabled them
