### ISSUE TITLE
Backport Hardening Code to 10-stable

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#128]
Put in a new branch: hardened/experimental/10-stable

**Comment by opntr** [comment]
missing parts are:
* PIE/PIC in bsd.mk.*
* secadm hook in rtld
* documentation

**Comment by lattera** [comment]
PIE framework is now in place. secadm hooks installed. Last missing piece is documentation

**Comment by opntr** [comment]
Cool!
