### ISSUE TITLE
GPU based malwares 

### ISSUE THREAD

**Issue by opntr** [HardenedBSD/hardenedBSD#130]
18:57 @Zer0P http://haxpo.nl/haxpo2015ams/sessions/direct-x-direct-way-to-microsoft-windows-kernel/
18:57 @Zer0P https://github.com/x0r1/Demon
18:58 @Zer0P https://github.com/x0r1/Jellyfish

**Comment by ColinGilbert** [comment]
I think the only feasible solution to such attacks would be to run untrusted executables on a DMZ'd machine and screencast to the desktop via a hardened proxy.
