### ISSUE TITLE
shared-object randomization sometimes breaks privoxy startup

### ISSUE THREAD

**Issue by opntr** [HardenedBSD/hardenedBSD#137]

**Comment by lattera** [comment]
Interesting. What are the symptoms?

**Comment by opntr** [comment]
http://jenkins.hardenedbsd.org/~op/hardenedbsd/issue/137/

the privoxy randomly dies, because the libpcre not loaded in time...

**Comment by opntr** [comment]
* pass p_pax on aux - AT_PAX
* sanitize

**Comment by lattera** [comment]
We'll want to make sure that AT_PAX is properly sanitized prior to running any .so ctors entries.

**Comment by opntr** [comment]
Working fine after added the PAX_NOTE_{,NO}SHLIBRANDOM and the related secadm extension (https://github.com/HardenedBSD/secadm/commit/76d7cc15f6f0b6fe463dd0622b1fe1e1306f02b1).
