### ISSUE TITLE
ASLR + NOEXEC fixes required after latest mmap changes from jhb

### ISSUE THREAD

**Issue by opntr** [HardenedBSD/hardenedBSD#138]
https://github.com/freebsd/freebsd/commit/bba1e1e047f57e141ca66bc44e520fdd2f3c86a2

**Comment by opntr** [comment]
Do not close this bug, until jhb's change is not in 10-STABLE and this stuff not merged back.

**Comment by lattera** [comment]
Can this be closed?

**Comment by opntr** [comment]
Yes
