### ISSUE TITLE
ASLR not implemented on ARM64

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#154]
root@:~ # ps wwaux | grep sshd
	root  10201   0.0  0.0 16584 1784  -  Is   23:05    0:00.06 /usr/sbin/sshd
	root  48517   0.0  0.1 10508 2188 u0  S+   23:07    0:00.11 grep sshd
	root@:~ # procstat -v 10201
	PID              START                END PRT  RES PRES REF SHD FLAG TP PATH
	10201           0x100000           0x146000 r-x   54   59   2   1 CN-- vn /usr/sbin/sshd
	10201           0x156000           0x158000 rw-    2    0   1   0 C--- vn /usr/sbin/sshd
	10201           0x158000           0x160000 rw-    8    8   1   0 C--- df 
	10201         0x40156000         0x4016e000 r-x   24   27  10   0 CN-- vn /libexec/ld-elf.so.1
	10201         0x4016e000         0x40176000 rw-    8    8   1   0 C--- df 
	10201         0x4017e000         0x40180000 rw-    2    2   1   0 CN-- df 
	10201         0x40180000         0x40197000 r-x   23   24   4   2 CN-- vn /usr/lib/libbsm.so.3
	10201         0x40197000         0x401a6000 ---    0    0   1   0 CN-- df 
	10201         0x401a6000         0x401a8000 rw-    2    0   1   0 CN-- vn /usr/lib/libbsm.so.3
	10201         0x401a8000         0x401b3000 r-x   11   12   6   3 CN-- vn /usr/lib/libpam.so.5
	10201         0x401b3000         0x401c3000 ---    0    0   1   0 CN-- df 
	10201         0x401c3000         0x401c4000 rw-    1    0   1   0 CN-- vn /usr/lib/libpam.so.5
	10201         0x401c4000         0x40340000 r-x  380  421   6   3 CN-- vn /lib/libcrypto.so.7
	10201         0x40340000         0x40350000 ---    0    0   1   0 CN-- df 
	10201         0x40350000         0x40377000 rw-   39    0   1   0 CN-- vn /lib/libcrypto.so.7
	10201         0x40377000         0x40379000 rw-    1    1   1   0 CN-- df 
	10201         0x40379000         0x403f7000 r-x  126  131   2   1 CN-- vn /usr/lib/libprivatessh.so.5
	10201         0x403f7000         0x40407000 ---    0    0   1   0 CN-- df 
	10201         0x40407000         0x4040a000 rw-    3    0   1   0 C--- vn /usr/lib/libprivatessh.so.5
	10201         0x4040a000         0x4040c000 rw-    1    1   1   0 C--- df 
	10201         0x4040c000         0x40543000 r-x  311  325  19   9 CN-- vn /lib/libc.so.7
	10201         0x40543000         0x40553000 ---    0    0   1   0 CN-- df 
	10201         0x40553000         0x4055f000 rw-   12    0   1   0 C--- vn /lib/libc.so.7
	10201         0x4055f000         0x40578000 rw-    9    9   1   0 C--- df 
	10201         0x40578000         0x40580000 r-x    8    9   6   3 CN-- vn /usr/lib/libwrap.so.6
	10201         0x40580000         0x40590000 ---    0    0   1   0 CN-- df 
	10201         0x40590000         0x40591000 rw-    1    0   1   0 CN-- vn /usr/lib/libwrap.so.6
	10201         0x40591000         0x405a0000 r-x   15   16  18   9 CN-- vn /lib/libutil.so.9
	10201         0x405a0000         0x405af000 ---    0    0   1   0 CN-- df 
	10201         0x405af000         0x405b1000 rw-    2    0   1   0 CN-- vn /lib/libutil.so.9
	10201         0x405b1000         0x405b2000 rw-    0    0   0   0 ---- -- 
	10201         0x405b2000         0x405ba000 r-x    8    8   2   1 CN-- vn /usr/lib/libgssapi.so.10
	10201         0x405ba000         0x405c9000 ---    0    0   1   0 CN-- df 
	10201         0x405c9000         0x405ca000 rw-    1    0   1   0 CN-- vn /usr/lib/libgssapi.so.10
	10201         0x405ca000         0x405e3000 r-x   25   28   2   1 CN-- vn /lib/libthr.so.3
	10201         0x405e3000         0x405f2000 ---    0    0   1   0 CN-- df 
	10201         0x405f2000         0x405f4000 rw-    2    0   1   0 C--- vn /lib/libthr.so.3
	10201         0x405f4000         0x405ff000 rw-   11   11   1   0 C--- df 
	10201         0x405ff000         0x40662000 r-x   56   63   2   1 CN-- vn /usr/lib/libkrb5.so.11
	10201         0x40662000         0x40672000 ---    0    0   1   0 CN-- df 
	10201         0x40672000         0x40677000 rw-    5    0   1   0 CN-- vn /usr/lib/libkrb5.so.11
	10201         0x40677000         0x40691000 r-x   25   28   2   1 CN-- vn /usr/lib/libgssapi_krb5.so.10
	10201         0x40691000         0x406a0000 ---    0    0   1   0 CN-- df 
	10201         0x406a0000         0x406a2000 rw-    2    0   1   0 CN-- vn /usr/lib/libgssapi_krb5.so.10
	10201         0x406a2000         0x406b5000 r-x   17   17   2   1 CN-- vn /lib/libz.so.6
	10201         0x406b5000         0x406c4000 ---    0    0   1   0 CN-- df 
	10201         0x406c4000         0x406c5000 rw-    1    0   1   0 CN-- vn /lib/libz.so.6
	10201         0x406c5000         0x406ce000 rw-    9    9   1   0 C--- df 
	10201         0x406ce000         0x406db000 r-x   13   13   6   3 CN-- vn /lib/libcrypt.so.5
	10201         0x406db000         0x406ea000 ---    0    0   1   0 CN-- df 
	10201         0x406ea000         0x406eb000 rw-    1    0   1   0 CN-- vn /lib/libcrypt.so.5
	10201         0x406eb000         0x406fc000 rw-    0    0   0   0 ---- -- 
	10201         0x406fc000         0x40745000 r-x   33   40   2   1 CN-- vn /usr/lib/libprivateldns.so.5
	10201         0x40745000         0x40754000 ---    0    0   1   0 CN-- df 
	10201         0x40754000         0x4075a000 rw-    6    0   1   0 CN-- vn /usr/lib/libprivateldns.so.5
	10201         0x4075a000         0x40781000 r-x   17   19   2   1 CN-- vn /usr/lib/libwind.so.11
	10201         0x40781000         0x40790000 ---    0    0   1   0 CN-- df 
	10201         0x40790000         0x40791000 rw-    1    0   1   0 CN-- vn /usr/lib/libwind.so.11
	10201         0x40791000         0x407a0000 r-x   15   16   2   1 CN-- vn /usr/lib/libroken.so.11
	10201         0x407a0000         0x407b0000 ---    0    0   1   0 CN-- df 
	10201         0x407b0000         0x407b1000 rw-    1    0   1   0 CN-- vn /usr/lib/libroken.so.11
	10201         0x407b1000         0x407b3000 r-x    2    2   2   1 CN-- vn /usr/lib/libprivateheimipcc.so.11
	10201         0x407b3000         0x407c2000 ---    0    0   1   0 CN-- df 
	10201         0x407c2000         0x407c3000 rw-    1    0   1   0 CN-- vn /usr/lib/libprivateheimipcc.so.11
	10201         0x407c3000         0x407c4000 r-x    1    2   2   1 CN-- vn /usr/lib/libcom_err.so.5
	10201         0x407c4000         0x407d4000 ---    0    0   1   0 CN-- df 
	10201         0x407d4000         0x407d5000 rw-    1    0   1   0 CN-- vn /usr/lib/libcom_err.so.5
	10201         0x407d5000         0x40852000 r-x   45   49   2   1 CN-- vn /usr/lib/libasn1.so.11
	10201         0x40852000         0x40861000 ---    0    0   1   0 CN-- df 
	10201         0x40861000         0x40864000 rw-    3    0   1   0 CN-- vn /usr/lib/libasn1.so.11
	10201         0x40864000         0x40867000 r-x    3    3   2   1 CN-- vn /usr/lib/libheimbase.so.11
	10201         0x40867000         0x40876000 ---    0    0   1   0 CN-- df 
	10201         0x40876000         0x40877000 rw-    1    0   1   0 CN-- vn /usr/lib/libheimbase.so.11
	10201         0x40877000         0x408b5000 r-x   38   43   2   1 CN-- vn /usr/lib/libhx509.so.11
	10201         0x408b5000         0x408c4000 ---    0    0   1   0 CN-- df 
	10201         0x408c4000         0x408c8000 rw-    4    0   1   0 CN-- vn /usr/lib/libhx509.so.11
	10201         0x408c8000         0x4091f000 rw-   79   79   1   0 CN-- df 
	10201         0x40c00000         0x41400000 rw-  212  212   1   0 C--- df 
	10201       0x7fbffff000       0x7fc0000000 ---    0    0   0   0 ---- -- 
	10201       0x7ffffe0000       0x8000000000 rw-    5    5   1   0 C--D df 
	root@:~ # service sshd onerestart
	Performing sanity check on sshd configuration.
	Stopping sshd.
	Performing sanity check on sshd configuration.
	Starting sshd.
	root@:~ # ps wwaux | grep sshd
	root  64561  4.0  0.0 16596 1760  -  Ss   23:07    0:00.06 /usr/sbin/sshd
	root  91691  0.0  0.1 10508 2188 u0  S+   23:07    0:00.04 grep sshd
	root@:~ # procstat -v 64561
	PID              START                END PRT  RES PRES REF SHD FLAG TP PATH
	64561           0x100000           0x146000 r-x   54   59   2   1 CN-- vn /usr/sbin/sshd
	64561           0x156000           0x158000 rw-    2    0   1   0 C--- vn /usr/sbin/sshd
	64561           0x158000           0x160000 rw-    8    8   1   0 C--- df 
	64561         0x40156000         0x4016e000 r-x   24   27  10   0 CN-- vn /libexec/ld-elf.so.1
	64561         0x4016e000         0x40176000 rw-    8    8   1   0 C--- df 
	64561         0x4017e000         0x40180000 rw-    2    2   1   0 CN-- df 
	64561         0x40180000         0x40188000 r-x    8    8   2   1 CN-- vn /usr/lib/libgssapi.so.10
	64561         0x40188000         0x40197000 ---    0    0   1   0 CN-- df 
	64561         0x40197000         0x40198000 rw-    1    0   1   0 CN-- vn /usr/lib/libgssapi.so.10
	64561         0x40198000         0x401a0000 r-x    8    9   6   3 CN-- vn /usr/lib/libwrap.so.6
	64561         0x401a0000         0x401b0000 ---    0    0   1   0 CN-- df 
	64561         0x401b0000         0x401b1000 rw-    1    0   1   0 CN-- vn /usr/lib/libwrap.so.6
	64561         0x401b1000         0x40214000 r-x   56   63   2   1 CN-- vn /usr/lib/libkrb5.so.11
	64561         0x40214000         0x40224000 ---    0    0   1   0 CN-- df 
	64561         0x40224000         0x40229000 rw-    5    0   1   0 CN-- vn /usr/lib/libkrb5.so.11
	64561         0x40229000         0x40234000 r-x   11   12   6   3 CN-- vn /usr/lib/libpam.so.5
	64561         0x40234000         0x40244000 ---    0    0   1   0 CN-- df 
	64561         0x40244000         0x40245000 rw-    1    0   1   0 CN-- vn /usr/lib/libpam.so.5
	64561         0x40245000         0x4025f000 r-x   25   28   2   1 CN-- vn /usr/lib/libgssapi_krb5.so.10
	64561         0x4025f000         0x4026e000 ---    0    0   1   0 CN-- df 
	64561         0x4026e000         0x40270000 rw-    2    0   1   0 CN-- vn /usr/lib/libgssapi_krb5.so.10
	64561         0x40270000         0x402ee000 r-x  126  131   2   1 CN-- vn /usr/lib/libprivatessh.so.5
	64561         0x402ee000         0x402fe000 ---    0    0   1   0 CN-- df 
	64561         0x402fe000         0x40301000 rw-    3    0   1   0 C--- vn /usr/lib/libprivatessh.so.5
	64561         0x40301000         0x40303000 rw-    1    1   1   0 C--- df 
	64561         0x40303000         0x40312000 r-x   15   16  18   9 CN-- vn /lib/libutil.so.9
	64561         0x40312000         0x40321000 ---    0    0   1   0 CN-- df 
	64561         0x40321000         0x40323000 rw-    2    0   1   0 CN-- vn /lib/libutil.so.9
	64561         0x40323000         0x40324000 rw-    0    0   0   0 ---- -- 
	64561         0x40324000         0x4045b000 r-x  311  325  19   9 CN-- vn /lib/libc.so.7
	64561         0x4045b000         0x4046b000 ---    0    0   1   0 CN-- df 
	64561         0x4046b000         0x40477000 rw-   12    0   1   0 C--- vn /lib/libc.so.7
	64561         0x40477000         0x40490000 rw-    9    9   1   0 C--- df 
	64561         0x40490000         0x404a9000 r-x   25   28   2   1 CN-- vn /lib/libthr.so.3
	64561         0x404a9000         0x404b8000 ---    0    0   1   0 CN-- df 
	64561         0x404b8000         0x404ba000 rw-    2    0   1   0 C--- vn /lib/libthr.so.3
	64561         0x404ba000         0x404c5000 rw-   11   11   1   0 C--- df 
	64561         0x404c5000         0x40641000 r-x  380  421   6   3 CN-- vn /lib/libcrypto.so.7
	64561         0x40641000         0x40651000 ---    0    0   1   0 CN-- df 
	64561         0x40651000         0x40678000 rw-   39    0   1   0 CN-- vn /lib/libcrypto.so.7
	64561         0x40678000         0x4067a000 rw-    1    1   1   0 CN-- df 
	64561         0x4067a000         0x40691000 r-x   23   24   4   2 CN-- vn /usr/lib/libbsm.so.3
	64561         0x40691000         0x406a0000 ---    0    0   1   0 CN-- df 
	64561         0x406a0000         0x406a2000 rw-    2    0   1   0 CN-- vn /usr/lib/libbsm.so.3
	64561         0x406a2000         0x406e0000 r-x   38   43   2   1 CN-- vn /usr/lib/libhx509.so.11
	64561         0x406e0000         0x406ef000 ---    0    0   1   0 CN-- df 
	64561         0x406ef000         0x406f3000 rw-    4    0   1   0 CN-- vn /usr/lib/libhx509.so.11
	64561         0x406f3000         0x406fc000 rw-    9    9   1   0 C--- df 
	64561         0x406fc000         0x40779000 r-x   45   49   2   1 CN-- vn /usr/lib/libasn1.so.11
	64561         0x40779000         0x40788000 ---    0    0   1   0 CN-- df 
	64561         0x40788000         0x4078b000 rw-    3    0   1   0 CN-- vn /usr/lib/libasn1.so.11
	64561         0x4078b000         0x4078e000 r-x    3    3   2   1 CN-- vn /usr/lib/libheimbase.so.11
	64561         0x4078e000         0x4079d000 ---    0    0   1   0 CN-- df 
	64561         0x4079d000         0x4079e000 rw-    1    0   1   0 CN-- vn /usr/lib/libheimbase.so.11
	64561         0x4079e000         0x407c5000 r-x   17   19   2   1 CN-- vn /usr/lib/libwind.so.11
	64561         0x407c5000         0x407d4000 ---    0    0   1   0 CN-- df 
	64561         0x407d4000         0x407d5000 rw-    1    0   1   0 CN-- vn /usr/lib/libwind.so.11
	64561         0x407d5000         0x407d7000 r-x    2    2   2   1 CN-- vn /usr/lib/libprivateheimipcc.so.11
	64561         0x407d7000         0x407e6000 ---    0    0   1   0 CN-- df 
	64561         0x407e6000         0x407e7000 rw-    1    0   1   0 CN-- vn /usr/lib/libprivateheimipcc.so.11
	64561         0x407e7000         0x407e8000 r-x    1    2   2   1 CN-- vn /usr/lib/libcom_err.so.5
	64561         0x407e8000         0x407f8000 ---    0    0   1   0 CN-- df 
	64561         0x407f8000         0x407f9000 rw-    1    0   1   0 CN-- vn /usr/lib/libcom_err.so.5
	64561         0x407f9000         0x40806000 r-x   13   13   6   3 CN-- vn /lib/libcrypt.so.5
	64561         0x40806000         0x40815000 ---    0    0   1   0 CN-- df 
	64561         0x40815000         0x40816000 rw-    1    0   1   0 CN-- vn /lib/libcrypt.so.5
	64561         0x40816000         0x40827000 rw-    0    0   0   0 ---- -- 
	64561         0x40827000         0x40836000 r-x   15   16   2   1 CN-- vn /usr/lib/libroken.so.11
	64561         0x40836000         0x40846000 ---    0    0   1   0 CN-- df 
	64561         0x40846000         0x40847000 rw-    1    0   1   0 CN-- vn /usr/lib/libroken.so.11
	64561         0x40847000         0x4085a000 r-x   17   17   2   1 CN-- vn /lib/libz.so.6
	64561         0x4085a000         0x40869000 ---    0    0   1   0 CN-- df 
	64561         0x40869000         0x4086a000 rw-    1    0   1   0 CN-- vn /lib/libz.so.6
	64561         0x4086a000         0x408b3000 r-x   33   40   2   1 CN-- vn /usr/lib/libprivateldns.so.5
	64561         0x408b3000         0x408c2000 ---    0    0   1   0 CN-- df 
	64561         0x408c2000         0x408c8000 rw-    6    0   1   0 CN-- vn /usr/lib/libprivateldns.so.5
	64561         0x408c8000         0x40922000 rw-   79   79   1   0 CN-- df 
	64561         0x40c00000         0x41400000 rw-  212  212   1   0 C--- df 
	64561       0x7fbffff000       0x7fc0000000 ---    0    0   0   0 ---- -- 
	64561       0x7ffffe0000       0x8000000000 rw-    5    5   1   0 C--D df 
    root@:~ # sysctl hardening
    hardening.procfs_harden: 1
    hardening.allow_map32bit: 0
    hardening.log.ulog: 0
    hardening.log.log: 1
    hardening.version: 28
    hardening.pax.mprotect.status: 2
    hardening.pax.pageexec.status: 2
    hardening.pax.aslr.vdso_len: 20
    hardening.pax.aslr.exec_len: 30
    hardening.pax.aslr.stack_len: 42
    hardening.pax.aslr.mmap_len: 30
    hardening.pax.aslr.status: 2

**Comment by opntr** [comment]
try with the latest head

**Comment by lattera** [comment]
Getting closer:

    WARNING: WITNESS option enabled, expect reduced performance.
    Trying to mount root from ufs:/dev/vtbd0s2 [rw,noatime]...
    warning: no time-of-day clock registered, system time will not be set accurately
    [PAX ASLR] failed to map the main stack @0xfffff9260560b000
    -> pid: 1 ppid: 0 p_pax: 0x145<PAGEEXEC,MPROTECT,ASLR,SHLIBRANDOM> 
    panic: mutex Giant owned at /usr/src/sys/kern/kern_exit.c:194
    cpuid = 0
    KDB: stack backtrace:
    db_trace_self() at db_trace_self_wrapper+0x28
            pc = 0xffffff80003fcb2c  lr = 0xffffff8000042184
            sp = 0xffffff8093e9b450  fp = 0xffffff8093e9b570

    db_trace_self_wrapper() at vpanic+0x14c
            pc = 0xffffff8000042184  lr = 0xffffff8000183e30
            sp = 0xffffff8093e9b580  fp = 0xffffff8093e9b5f0

    vpanic() at panic+0x4c
            pc = 0xffffff8000183e30  lr = 0xffffff8000183ec4
            sp = 0xffffff8093e9b600  fp = 0xffffff8093e9b680

    panic() at __mtx_assert+0xd8
            pc = 0xffffff8000183ec4  lr = 0xffffff800016a1c4
            sp = 0xffffff8093e9b690  fp = 0xffffff8093e9b690

    __mtx_assert() at exit1+0x48
            pc = 0xffffff800016a1c4  lr = 0xffffff8000148f74
            sp = 0xffffff8093e9b6a0  fp = 0xffffff8093e9b730

    exit1() at kern_execve+0x740
            pc = 0xffffff8000148f74  lr = 0xffffff80001470a8
            sp = 0xffffff8093e9b740  fp = 0xffffff8093e9ba60

    kern_execve() at sys_execve+0x54
            pc = 0xffffff80001470a8  lr = 0xffffff8000146600
            sp = 0xffffff8093e9ba70  fp = 0xffffff8093e9bae0

    sys_execve() at start_init+0x234
            pc = 0xffffff8000146600  lr = 0xffffff800012ad30
            sp = 0xffffff8093e9baf0  fp = 0xffffff8093e9bb70

    start_init() at fork_exit+0x7c
            pc = 0xffffff800012ad30  lr = 0xffffff800014d75c
            sp = 0xffffff8093e9bb80  fp = 0xffffff8093e9bbb0

    fork_exit() at fork_trampoline+0x10
            pc = 0xffffff800014d75c  lr = 0xffffff800040b678
            sp = 0xffffff8093e9bbc0  fp = 0x0000000000000000

    KDB: enter: panic
    [ thread pid 1 tid 100002 ]

**Comment by lattera** [comment]
Interesting ARM64 macros to look at: https://github.com/HardenedBSD/hardenedBSD/blob/hardened/current/master/sys/arm64/include/vmparam.h#L152-L164

**Comment by lattera** [comment]
This is because we're randomizing too many bits by default on ARM64. Our default of 42 is too high. Issue #155 would help address this issue.

**Comment by opntr** [comment]
In theory, since the latest commits, it works.
