### ISSUE TITLE
Per-Arch ASLR Includes

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#155]
Our ASLR macros are all shoved in at the top of sys/hardenedbsd/hbsd_pax_aslr.c. The majority of these macros are 64-bit and 32-bit sensitive. We're seeing different results on ARM64 versus AMD64, so even different settings need to be applied on different 64-bit architectures. Placing these macros in architecture-dependent macros (kinda like how ELF machdep macros are done) will allow us to keep our macros organized in a sane fashion and allow us more flexibility and portability.

**Comment by opntr** [comment]
Just add options PAX_ASLR_DELTA_{EXEC,MMAP,STACK,VDSO}_DEF_LEN=N to the specific kernel config to override the default settings.

https://github.com/HardenedBSD/hardenedBSD/blob/hardened/current/master/sys/hardenedbsd/hbsd_pax_aslr.c#L160

**Comment by lattera** [comment]
Closing this since this is now complete.
