### ISSUE TITLE
generate and add /boot/entropy file to installers

### ISSUE THREAD

**Issue by opntr** [HardenedBSD/hardenedBSD#156]

**Comment by opntr** [comment]
http://jenkins.hardenedbsd.org/~op/HardenedBSD-11-CURRENT_hardenedbsd-master-amd64-memstick-randomfix.img

**Comment by shirkdog** [comment]
11.0-CURRENT-HBSD FreeBSD 11.0-CURRENT-HBSD #4 bd7e411(hardened/current/unstable): Sat Aug 22 17:04:23 EDT 2015  rebooted 10 times it does not hang, /boot/entropy exists with 4096 bytes
