### ISSUE TITLE
SIGABRT with Erlang (18.0.3) applications.

### ISSUE THREAD

**Issue by dmilith** [HardenedBSD/hardenedBSD#157]
I've found (thanks to Zer0P for suggestions), that `hardening.allow_map32bit` sysctl feature must be set to 1, to avoid problem with SIGABRT thrown from Erlang VM (when building Elixir in this case).

I'm using 10-STABLE branch with 64bit machine.

**Comment by dmilith** [comment]
Moved to https://github.com/HardenedBSD/secadm-rules/issues/2

**Comment by lattera** [comment]
I should make the map32bit setting be able to be applied per-process. This will require changes on HardenedBSD's side, not just with secadm. Good catch.

**Comment by lattera** [comment]
This is now done on 11-CURRENT. I'll backport to 10-STABLE within the next few weeks.

**Comment by dmilith** [comment]
Great. Thanks!
