### ISSUE TITLE
Build Error on commit a69ca452643a0ee2f4033620a55f6f3ed6f67b73

### ISSUE THREAD

**Issue by 2trill2spill** [HardenedBSD/hardenedBSD#159]
Building the kernel fails on the latest commit. Below is part of the error message.

```
CC='cc  ' mkdep -f .depend -a   -nostdinc -DHARDENEDBSD -D_KERNEL -DKLD_MODULE -   DHAVE_KERNEL_OPTION_HEADERS -I. -I/usr/home/nah/hardenedBSD/sys -I/usr/obj/usr/home/nah/hardenedBSD/sys/GENERIC -D__printf__=__freebsd_kprintf__ -std=iso9899:1999   /usr/home/nah/hardenedBSD/sys/modules/nvram/../../dev/nvram/nvram.c
--- depend_subdir_oce ---
make[4]: make[4]: don't know how to make oce_if.c. Stop

make[4]: stopped in /usr/home/nah/hardenedBSD/sys/modules/oce
*** [depend_subdir_oce] Error code 2
```

The full output of the kernel build can be found here: https://mega.nz/#!wc9UwLAQ!5zFN0Jj0G0wdhzX88dz8CwwhlKzSSR73W5BnvkKuZ6Y

**Comment by opntr** [comment]
We sync the HardenedBSD/HardenedBSD.git repo to FreeBSD/FreeBSD repo in every 6 hours, so it's probably a build breakage in FreeBSD's HEAD.

Try HardenedBSD/HardenedBSD-stable.git or wait 6 hours instead.

**Comment by opntr** [comment]
One of the latest commits from imp (bsdimp) in FreeBSD/FreeBSD repo, which is merged to HardenedBSD/HardenedBSD should fix this issue

**Comment by 2trill2spill** [comment]
Yea It builds now, thanks for responding.
