### ISSUE TITLE
not installed /boot/entropy file

### ISSUE THREAD

**Issue by opntr** [HardenedBSD/hardenedBSD#167]
Discussed with @jmgurney and hunger.

The current FreeBSD installer not installed the /boot/entropy file at the end of the install. Fix them.

**Comment by jmgurney** [comment]
Yeh, adding a simple:
dd if=/dev/random of=$BSDINSTALL_CHROOT/boot/entropy bs=4096 count=1

Should do it...

I think we should also add chown 0:0 and chmod 600 for both the files too just to be careful.

**Comment by jmgurney** [comment]
Ok, created patch  in jmgurney/bootrng:807bcbcdcb8767589691a80a7fc5431f42a605be.  Only tested by manually setting the env var and running.  Have not done a full install test.

**Comment by jmgurney** [comment]
Created https://reviews.freebsd.org/D3933

**Comment by opntr** [comment]
We already committed the change.
