### ISSUE TITLE
mac_seeotheruids.ko is broken?

### ISSUE THREAD

**Issue by feld** [HardenedBSD/hardenedBSD#185]
I use mac_seeotheruids to hide processes users don't own. This can also be achieved with security.bsd.see_other_uids sysctl, but that does not let you permit any users to be exempt from this restriction.

I have noticed that the default on hbsd is security.bsd.see_other_uids=0, vs =1 for FreeBSD

I have my machines setup so the monitoring software can see all processes on the system with the following sysctls when mac_seeotheruids is loaded:

security.bsd.see_other_uids=1
security.mac.seeotheruids.enabled=1
security.mac.seeotheruids.specificgid_enabled=1
security.mac.seeotheruids.specificgid=280

This does not seem to be working as expected for me. My monitoring software using gid 280 cannot see all processes on the system while other non-root users have the processes hidden.

**Comment by feld** [comment]
I also forgot to note that mac_seeotheruids_enable="YES" in loader.conf is no longer working either.

**Comment by feld** [comment]
Ok, it's not broken -- i also need to set security.bsd.see_other_gids=1 first

Why it's not loading on boot is still a mystery

**Comment by opntr** [comment]
please reopen the issue, if still exists

**Comment by feld** [comment]
I had a typo in my loader.conf that was causing the problem.
