### ISSUE TITLE
Adapt Live DVDs to HardenedBSD

### ISSUE THREAD

**Issue by xmj** [HardenedBSD/hardenedBSD#192]
Tweaks necessary to make dvd1.iso give you a working Live DVD:

https://github.com/HardenedBSD/hardenedBSD/blob/hardened/current/master/release/pkg_repos/release-dvd.conf
currently contains a link to pkg.freebsd.org. Should probably be replaced as a whole with pkg.hardenedbsd.org.

Current HBSD LiveDVDs
https://github.com/HardenedBSD/hardenedBSD/blob/hardened/current/master/release/scripts/pkg-stage.sh#L17
contain at least one package with outstanding vulnerabilites -- `linux_base-f10`.
Probably best to remove this line outright.

Upstream PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208280

**Comment by opntr** [comment]
(not yet fully fixed)

**Comment by xmj** [comment]
Closing in favor of https://github.com/HardenedBSD/hardenedBSD/issues/253
