### ISSUE TITLE
Optionally Randomize MAC Addresses

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#194]
This would be great general hardening for those who want network anonymity.

**Comment by Andrew415** [comment]
I like this too but many networks require static MAC addresses for dhcp or ARP whitelisting.

**Comment by lattera** [comment]
Yup. That's why if this feature is implemented, it would be optional.

**Comment by lattera** [comment]
This was done upstream. Closing this ticket.
