### ISSUE TITLE
hbsd-update: custom kernel detection

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#196]
hbsd-update currently assumes the user is running the kernel specified in `hbsd-update.conf(5)`. Instead, follow this logic:

1. Download update archive
1. Detect kernels in update archive
1. Match current kernel to list of kernels in update archive
    1. If no match, use the kernel in `hbsd-update.conf(5)`
        1. If still no match, error out
        1. If match, use the matched kernel
    1. If match, use the matched kernel

**Comment by lattera** [comment]
This issue inspired by @xmj.

**Comment by xmj** [comment]
Logic behind 3:

val=$(uname -v); val=${val##*/}
1. check if $val is in update.txz
2. if it isn't, check if "kernel" setting from /etc/hbsd-update.conf is in update.txz
3. if that isn't, fall back to HARDENEDBSD

**Comment by lattera** [comment]
Now that this has been MFC'd, this issue is now finished.
