### ISSUE TITLE
OpenSSL/LibreSSL ObsoleteFiles

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#210]
In the hardened/*/master-libressl branch, we should use ObsoleteFiles.inc to delete files/directories from OpenSSL that don't pertain to LibreSSL when LibreSSL is enabled and vice-versa. This means we need to keep an inventory of all files OpenSSL installs and all files LibreSSL installs.

ObsoleteFiles.inc supports src.opts.mk/bsd.opts.mk, so we can toggle off of MK_LIBRESSL.

**Comment by Sp1l** [comment]
Closed by 793b647b264608655e89e6a96ce08b7a574ac3ea and 6670850971225cfb3f1860ae9b53cf1ce55f0520
