### ISSUE TITLE
use unbound-host instead of drill in hbsd-update

### ISSUE THREAD

**Issue by Habbie** [HardenedBSD/hardenedBSD#213]
drill was made for debugging; unbound (and by extension, unbound-host) was made to actually turn DNSSEC into protection; therefore, I suggest hbsd-update should be using unbound-host (-v -f etc.) instead of drill. The unbound-host sources are in the (upstream) tree, but it is not currently being compiled. This should not be hard to fix.

**Comment by lattera** [comment]
This is now complete. Closing the issue. Thanks for the suggestion!
