### ISSUE TITLE
Make the hardened/current/master-libressl branch the default

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#215]
I'm thinking it's time. @opntr and @Sp1l, thoughts?

- [x] Shawn
- [x] Olivér
- [x] Bernard

**Comment by Sp1l** [comment]
I haven't seen issues with this on my 10.3 nor my 11.0-RC1 system.
PC-BSD/TrueOS has been happy with it so far but that's still kind of fresh.

Do we know of the distribution of users of 10-stable vs. 11-stable vs. current? I'd assume a lot fewer users  of current and dogfooding would be great! :dog::fork_and_knife:

I'm in favor! (added as a task-list to record votes :smile:

**Comment by opntr** [comment]
ACK

**Comment by lattera** [comment]
Now that LibreSSL has been imported into hardened/current/master and is the default, I've switched the default branch back to hardened/current/master.
