### ISSUE TITLE
Cannot compile utrace.

### ISSUE THREAD

**Issue by raymontag** [HardenedBSD/hardenedBSD#219]
Hello,

I'm not able to compile utrace in /usr/src/lib/libsysdecode as the folder lacks the file "rtld_utrace.h". I'm encountering this on a fresh pull from hardened/11-stable/master-libressl

This blocks compiling /usr/src/

Best,

Karsten

**Comment by lattera** [comment]
We haven't made any chances to utrace or libsysdecode. Can you try compiling with vanilla FreeBSD sources?

**Comment by raymontag** [comment]
Sorry for the late answer: Yes, vanilla FreeBSD (I tried 11-stable) can compile.

**Comment by lattera** [comment]
What are the steps you're taking to compile utrace?

**Comment by lattera** [comment]
Is this still an issue for you?

**Comment by raymontag** [comment]
No, I didn't looked more into it. Probably I just did some mistake.
