### ISSUE TITLE
Insert random-sized gap between shared objects

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#221]
In talking with Peter Hessler, one thing that OpenBSD does is insert random-sized PROT_NONE gaps between shared objects. This helps increase entropy. I think this is a good idea, especially when combined with shared library load order randomization.

**Comment by opntr** [comment]
https://github.com/HardenedBSD/hardenedBSD/commit/8b0437606fd6c1d6ac69b6084674a408c7e83bee
https://github.com/HardenedBSD/hardenedBSD/commit/0c0d2c028264814cace4448f7427e5d468a63cf8
https://github.com/HardenedBSD/hardenedBSD/commit/24183afd6ee230d1706e24d2f6d30f3012fcd2ed
https://github.com/HardenedBSD/hardenedBSD/commit/ccc0396968b3fa2d1ae5391c96d2d4e7580ffdaf
https://github.com/HardenedBSD/hardenedBSD/commit/7930f48c3dfce9a3516dab02ed6d5ba84dd303b1
https://github.com/HardenedBSD/hardenedBSD/commit/88b1a8b95028eaabed9beaf4c367e1d69d737b9a
