### ISSUE TITLE
Optionally compile devd as a PIE

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#223]
`/sbin/devd` is currently compiled as a static binary due to depending on `/usr/lib/libc++.so.1`. Add a `WITH_DEVD_PIE` `src.conf(5)` flag to enable compiling `devd` as a Position-Independent Executable (PIE).

The reason to make it opt-in rather than simply compiling `devd` as a PIE is because `libc++` gets installed into `/usr/lib`. `/usr` may not be available by the time `devd` starts up. But for those users whose systems `/usr/lib` is part of `/`, `devd` would be safe to compile as a PIE.

**Comment by opntr** [comment]
NACK.

**Comment by lattera** [comment]
Why not?

**Comment by opntr** [comment]
I want to keep the system in consistent and bootable state.

**Comment by lattera** [comment]
Agreed. Which is why the toggle is off by default. For root-on-zfs installs, though, having devd compiled as a PIE would still be okay. I think if we provide enough warning in the `src.conf(5)` manpage, the user will understand the risks. Just as the user should understand the risks for `rm -rf /`.

But, if you feel strongly that not even a warning in `src.conf(5)` is sufficient, I'll revert.
