### ISSUE TITLE
"ELF interpreter /libexec/ld-elf.so.1 not found, error 8" after hbsd-update

### ISSUE THREAD

**Issue by oniichaNj** [HardenedBSD/hardenedBSD#225]
Opening this issue because IRC told me to.

I ran a hbsd-update, all seemed to go well, but when it finished, I got the error "ELF interpreter /libexec/ld-elf.so.1 not found, error 8" whenever I typed anything into my current running tcsh. 

My uname -a at the time of running hbsd-update: 
`FreeBSD host.domain.ninja 11.0-BETA3-HBSD FreeBSD 11.0-BETA3-HBSD #0 [STABLE:HardenedBSD-11-STABLE-v46]: Sun Jul 31 17:11:12 UTC 2016     root@nyi-01.build.hardenedbsd.org:/usr/obj/usr/src/sys/HARDENEDBSD  amd64`

Yeah, I know it's an old beta, that's why I updated.

**Comment by oniichaNj** [comment]
I slapped a new base.txz onto it from an install medium and ran another hbsd-update from that, which worked just fine, if that's any help.

**Comment by lattera** [comment]
I'm working on cleaning up some of our bug reports. Is this still an issue?

**Comment by oniichaNj** [comment]
I'm good.

**Comment by lattera** [comment]
Closing issue due to positive feedback from the reporter.
