### ISSUE TITLE
rethink the require_fs helper function in netbsd-tests

### ISSUE THREAD

**Issue by opntr** [HardenedBSD/hardenedBSD#228]
Remove the require_fs tmpfs @ https://github.com/HardenedBSD/hardenedBSD/blob/hardened/current/master/contrib/netbsd-tests/fs/tmpfs/h_funcs.subr#L40 . This fixes the test runs on FreeBSD.

The root of the problem is here: https://github.com/HardenedBSD/hardenedBSD/blob/hardened/current/master/contrib/netbsd-tests/fs/h_funcs.subr#L43 since the mount_tmpfs does not exists on FreeBSD.

CC: @yaneurabeya

**Comment by yaneurabeya** [comment]
On Wed, Dec 21, 2016 at 2:54 PM, Olivér Pintér <notifications@github.com>
wrote:

> Remove the require_fs tmpfs @ https://github.com/
> HardenedBSD/hardenedBSD/blob/hardened/current/master/
> contrib/netbsd-tests/fs/tmpfs/h_funcs.subr#L40 . This fixes the test runs
> on FreeBSD.
>
> The root of the problem is here: https://github.com/
> HardenedBSD/hardenedBSD/blob/hardened/current/master/
> contrib/netbsd-tests/fs/h_funcs.subr#L43 since the mount_tmpfs does not
> exists on FreeBSD.
>
> CC: @yaneurabeya <https://github.com/yaneurabeya>
>
This should already be handled via the make install rule. From
tests/sys/fs/Makefile:

18 h_funcs.subr: ${TESTSRC}/h_funcs.subr
19         cat ${.ALLSRC} | \
20             sed -e '/atf_require_prog mount_$${name}/d' >>${.TARGET}.tmp
21         mv ${.TARGET}.tmp ${.TARGET}
22

If this isn't working for whatever reason, please let me know.
-Ngie

**Comment by opntr** [comment]
Absolutely sure, the Makefaile already handle this. When I discovered the issue (the missing helpers, because the broken FILE{DIR,}S prefixes, I copied them manually to it's place. So this was a big user error.
