### ISSUE TITLE
safestack renders the system to unbootable state, when /usr is in different partition

### ISSUE THREAD

**Issue by opntr** [HardenedBSD/hardenedBSD#229]
For more details see the https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=215701 ticket.

**Comment by lattera** [comment]
Maybe I should install librt to /lib instead of /usr/lib.

**Comment by opntr** [comment]
But installing librt to /lib does not solves the overlinking.

**Comment by lattera** [comment]
SafeStack adds librt. The SafeStack runtime is contained within librt.

**Comment by opntr** [comment]
Sure, librt is one, but what's about the other libs?

ls with SafeStack:
~~~
op@opn ~> ldd /bin/ls 
/bin/ls:
        libxo.so.0 => /lib/libxo.so.0 (0x47cb7677000)
        libutil.so.9 => /lib/libutil.so.9 (0x47cb7892000)
        libncursesw.so.8 => /lib/libncursesw.so.8 (0x47cb7aa6000)
        libthr.so.3 => /lib/libthr.so.3 (0x47c75a79000)
        librt.so.1 => /usr/lib/librt.so.1 (0x47c75ca1000)
        libm.so.5 => /lib/libm.so.5 (0x47c75ea7000)
        libc.so.7 => /lib/libc.so.7 (0x47c760d2000)
~~~

ls without SafeStack:
~~~
op@blackbird ~> ldd /bin/ls
/bin/ls:
        libxo.so.0 => /lib/libxo.so.0 (0xf46fa0a000)
        libutil.so.9 => /lib/libutil.so.9 (0xf46fc26000)
        libncursesw.so.8 => /lib/libncursesw.so.8 (0xf46fe3a000)
        libc.so.7 => /lib/libc.so.7 (0xf46ee65000)
~~~

**Comment by opntr** [comment]
In an unthreaded application, why required to link to libthr? Even more, why required the libm?

**Comment by lattera** [comment]
librt brings in libthr. Since I'm not adding any ```-l``` flags, it's safe to assume SafeStack needs the extra libs.

```
$ ldd /usr/lib/librt.so.1
/usr/lib/librt.so.1:
        libthr.so.3 => /lib/libthr.so.3 (0x2f45f3dd000)
        libc.so.7 => /lib/libc.so.7 (0x2f45fa36000)
```

**Comment by opntr** [comment]
And why required the librt?

~~~
commit 22fb15cfe91543bc3721037d122a43e7b10c31a7
Author: davidxu <davidxu@FreeBSD.org>
Date:   Wed Mar 1 06:37:34 2006 +0000

    Bring in my initial version of POSIX realtime extension library.
    Current the library implements mqueue, timer and aio with SIGEV_THREAD
    notification supported.
    
    Earlier version reviewed by: deischen
~~~

This is the first commit: git log -- lib/librt

**Comment by lattera** [comment]
So all I'm doing is adding ```-fsanitize=safe-stack``` to ```CFLAGS```, ```CXXFLAGS```, and ```LDFLAGS```. It looks like clang/lld is the one adding those libraries. I myself am not adding them: https://github.com/HardenedBSD/hardenedBSD/blob/hardened/current/master/share/mk/bsd.prog.mk#L77-L85

**Comment by opntr** [comment]
Ok, that's fine that these libraries are not added explicitly, but I still would be very good to known, why they needed.

**Comment by lattera** [comment]
I'd guess that SafeStack's runtime depends on librt, librt references symbols in libthr. As for libm, I'm not sure.

**Comment by lattera** [comment]
To fix this bug, librt simply needs to be installed in /lib.

**Comment by opntr** [comment]
And I still think that this SafeStack stuff's best place is currently in 12-CURRENT and not in 11-STABLE or at least not enabled by default in 11-STABLE.
This breaks too many things. Now I try to reproduce an other error, where a get build failure on previously enabled SafeStack (WITH_STAFESTACK= in src.conf / the previous default) on build host, and then changed them off, and I get a big build error in bmake about missing safestack related symbols....

**Comment by lattera** [comment]
Interesting. Okay. I'll also do more digging in 11-STABLE's case.

**Comment by lattera** [comment]
Here's the reason for linking the extra libs:

https://github.com/HardenedBSD/hardenedBSD/blob/hardened/current/master/contrib/llvm/tools/clang/lib/Driver/Tools.cpp#L3094-L3105

https://llvm.org/bugs/show_bug.cgi?id=15823
