### ISSUE TITLE
invariants has to be enabled

### ISSUE THREAD

**Issue by chrcoluk** [HardenedBSD/hardenedBSD#236]
Invariants has a significant performance overhead so as such shouldnt be used on production syste,s

I noticed in the default kernel for hardenedbsd it is listed twice, with one of them commented out stating its only to be used in CURRENT.  I assumed the second instance was a mistake so removed it.

However upon compiling the kernel I am greeted with this.

> error: "HardenedBSD required enabled INVARIANTS in kernel

So is it the case that hardenedbsd requires this performance overhead in place to work?

**Comment by chrcoluk** [comment]
sure but please answer the question?

Given invariants triggers buggy behaviour on freebsd and is slower.

**Comment by opntr** [comment]
Add "options PAX_INSECURE_MODE" to your kernel config.

INVARIANTS enforces many checks what are good to have. If you would like to compile your kernel without them, Add the above option to your kernel config.
