### ISSUE TITLE
I have openssl in base instead of libressl

### ISSUE THREAD

**Issue by chrcoluk** [HardenedBSD/hardenedBSD#238]
The features page lists libressl as replaced openssl, yet I seem to just have openssl still.

I also checked the src folder and it has openssl files in there.

Is libressl supposed to be built by default or requires a switch?

**Comment by lattera** [comment]
LibreSSL is the default in base for 12-CURRENT only right now. We're discussing a plan of action for 11-STABLE and 10-STABLE.

**Comment by chrcoluk** [comment]
Ok thanks, perhaps it should be put on the features comparison page with a symbol of what is not default for STABLE?

I noticed I can make it use libressl with a flag in src.conf tho.

**Comment by opntr** [comment]
Add WITH_LIBRESSL= to src.conf or install from the libressl flavored installer.

**Comment by opntr** [comment]
Btw, this is the branch, what are you looking for: https://github.com/HardenedBSD/hardenedBSD/tree/hardened/11-stable/master-libressl

**Comment by chrcoluk** [comment]
ok so there is no plan to add this to the normal branch any time soon even without it been enabled by default? seems odd to have a entire separate branch for it but thanks, will use that branch going forward.

**Comment by lattera** [comment]
See this comment: https://github.com/HardenedBSD/hardenedBSD/issues/238#issuecomment-276054511

**Comment by chrcoluk** [comment]
if it helps your decision, I have not had any issues using libressl in base on my VM.

**Comment by opntr** [comment]
Now the libressl is the default in hardened/11-stable/master.
