### ISSUE TITLE
paxtest shows few things as vuln

### ISSUE THREAD

**Issue by chrcoluk** [HardenedBSD/hardenedBSD#242]
output below, is this expected?

root@shiva paxtest-freebsd # ./paxtest kiddie
PaXtest
Copyright(c) 2003-2014 by Peter Busser <peter@adamantix.org> and Brad Spengler <spender@grsecurity.net>
Copyright(c) 2015 by Oliver Pinter <op@hardenedbsd.org>
Released under the GNU Public Licence version 2 or later

Writing output to paxtest.log
It may take a while for the tests to complete
Test results:
PaXtest
Copyright(c) 2003-2014 by Peter Busser <peter@adamantix.org> and Brad Spengler <spender@grsecurity.net>
Copyright(c) 2015 by Oliver Pinter <op@hardenedbsd.org>
Released under the GNU Public Licence version 2 or later

Mode: kiddie
Uname: FreeBSD apocalypse.chrysalisnet.org 9.3-RELEASE-p10 FreeBSD 9.3-RELEASE-p10 #0 r279966: Fri Mar 13 21:08:46 GMT 2015     root@apocalypse.chrysalisnet.org:/usr/obj/usr/src/93/sys/APOC93  amd64
Compiler: gcc version 4.2.1 20070831 patched [FreeBSD]

Executable anonymous mapping             : Killed
Executable bss                           : Killed
Executable data                          : Killed
Executable heap                          : Killed
Executable stack                         : Killed
Executable shared library bss            : Killed
Executable shared library data           : Killed
Executable anonymous mapping (mprotect)  : Killed
Executable bss (mprotect)                : Killed
Executable data (mprotect)               : Killed
Executable heap (mprotect)               : Killed
Executable stack (mprotect)              : Killed
Executable shared library bss (mprotect) : Killed
Executable shared library data (mprotect): Killed
Writable text segments                   : Vulnerable
Anonymous mapping randomization test     : 30 quality bits (guessed)
Heap randomization test (ET_EXEC)        : 21 quality bits (guessed)
Heap randomization test (PIE)            : 22 quality bits (guessed)
Main executable randomization (ET_EXEC)  : No randomization
Main executable randomization (PIE)      : 30 quality bits (guessed)
Shared library randomization test        : 30 quality bits (guessed)
VDSO randomization test                  : 28 quality bits (guessed)
Stack randomization test (SEGMEXEC)      : 41 quality bits (guessed)
Stack randomization test (PAGEEXEC)      : 41 quality bits (guessed)
Arg/env randomization test (SEGMEXEC)    : 42 quality bits (guessed)
Arg/env randomization test (PAGEEXEC)    : 42 quality bits (guessed)
Randomization under memory exhaustion @~0: 30 bits (guessed)
Randomization under memory exhaustion @0 : 30 bits (guessed)
Return to function (strcpy)              : paxtest: return address contains a NULL byte.
Return to function (memcpy)              : Vulnerable
Return to function (strcpy, PIE)         : paxtest: return address contains a NULL byte.
Return to function (memcpy, PIE)         : Vulnerable

Also i had to compile this on a FreeBSD server that I have gcc installed as it wont compile very far on my HardenedBSD test box that has clang, it be cool if you guys could add this to ports maybe? Alongside something that checks binaries like checksec.

**Comment by opntr** [comment]
The ports part: please open a ticket in hardenedbsd-ports.

On vulns: known issues. They are only fixed with grsecurity's proprietary RAP gcc plugin, which isn't available, and never will be publicly.

On other side, please retry the paxtest: this will be fixed: " Writable text segments : Vulnerable".
