### ISSUE TITLE
Use HardenedBSD packages for DVD installs.

### ISSUE THREAD

**Issue by xmj** [HardenedBSD/hardenedBSD#253]
release/Makefile dvd1.iso target fetches a set of packages to be embedded in DVD ISOs. Usefulness is somewhat limited due to bsdinstall lacking proper package install capabilities, but we should still dogfood our own packges for our own builds.

I've fixed it in HardebedBSD-playground commit  https://github.com/HardenedBSD/hardenedBSD-playground/commit/fd2fee9d653230ef2939d663848b17c7b907025b

**Comment by lattera** [comment]
Cherry-picked with commit 1439c07176fcd0f65eb6e84e81daa3adeb5620a6.

**Comment by xmj** [comment]
Closing
