### ISSUE TITLE
Import OpenNTPd

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#255]
Just as we do with LibreSSL, provide OpenNTPd in base. In 12-CURRENT, make it the default NTP service.

**Comment by lattera** [comment]
This is mostly done. @Sp1l has done some amazing work so far.

What's currently left to do:

1. When MK_OPENNTPD is set to yes, make the bsdinstall services script toggle the openntpd service instead of ntpd.
1. Bump __HardenedBSD_version
1. Update UPDATING-HardenedBSD

`hbsd-update(8)` has already been updated to allow HardenedBSD to notify users they'll need to update their `/etc/rc.conf` file and switch `ntpd_enable` to `openntpd_enable`.

**Comment by lattera** [comment]
In order to MFC this to 11-STABLE and 10-STABLE, LibreSSL must also be in base. Which reminds me, MK_OPENNTPD should be set to "no" if MK_LIBRESSL is set to "no".

**Comment by Sp1l** [comment]
All 3 issues addressed :D Please test/verify
