### ISSUE TITLE
Where has /usr/lib32 gone?

### ISSUE THREAD

**Issue by utrenkner** [HardenedBSD/hardenedBSD#258]
I recently installed HardenedBSD-11-STABLE-v46.16 on a server. Today, I was trying to use py3-iocage to set up some jails but failed because the jail manager expects /iocage/releases/11-STABLE/root/usr/lib32 to exist (here my [issue at iocage](https://github.com/iocage/iocage/issues/127)).

Has lib32 been completely removed from HardenedBSD? I could not find any such info in recent release notes.

**Comment by lattera** [comment]
You'll need to compile a custom kernel with the COMPAT_FREEBSD32 option enabled along with world with WITH_LIB32 set in src.conf(5).
