### ISSUE TITLE
Unable to build binary update for 12-CURRENT

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#270]
```
tar: __CONCAT(__HBSD_KPI,-9761f81e42281bb260be21e95587b5e115f98a9b.tar: Cannot stat: No such file or directory
tar: --exclude: Cannot stat: No such file or directory
tar: --exclude: Cannot stat: No such file or directory
tar: ./success: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors
```

**Comment by lattera** [comment]
Commit 7862e92aff792b44b26362136eee6b5b86b183c5 should be MFC'd with eba3054d247bd3821fdf427b8fccaf2ae5e92e1d.

**Comment by opntr** [comment]
This will be a better fix:

{code}
git show hardened/current/master:sys/sys/pax.h | awk '/#define[[:space:]]__HardenedBSD_version/{print $3}' | sed -e 's/UL$//g'
{code}

same as I use in tools repo.

**Comment by lattera** [comment]
Ah, cool! I'll do a follow-up commit with that instead. Thanks!

**Comment by opntr** [comment]
any update on this issue?

**Comment by opntr** [comment]
ahh, this is already done
