### ISSUE TITLE
libressl merge to 11-stable 46.xx

### ISSUE THREAD

**Issue by chrcoluk** [HardenedBSD/hardenedBSD#273]
Some months back you guys said it was under consideration, I hoped that you had started adding it to your snapshot releases, but am I right those are still based on openssl? (for 11.x).

**Comment by lattera** [comment]
I owe @Sp1l some pieces of data. Here's the plan of action we've worked out:

1. Fix any major ports fallout, if any (this is the data that I owe @Sp1l)
1. Merge libressl into hardened/11-stable/master
1. Update hbsd-update.conf in the hardened/11-stable/master-libressl branch to point to hardened/11-stable/master
1. Deprecate the hardened/11-stable/master-libressl branch

**Comment by chrcoluk** [comment]
ok thanks

**Comment by opntr** [comment]
As of 2017.09.16. the libressl was merged back to 11-STABLE: https://github.com/HardenedBSD/hardenedBSD/commit/59acac488d225d60066779a5a63c269e85021952
