### ISSUE TITLE
static and PIE not working together for ports

### ISSUE THREAD

**Issue by chrcoluk** [HardenedBSD/hardenedBSD#274]
I remember in another issue report this was reported ages ago for bash and I think shawn fixed it, However on the latest ports data from git, on both ccache and bash I get a segfault during the configure stage if static and pie are enabled together.

This is using base compiler 11-libressl branch.

snapshot of log for bash, is more or less same for ccache

`checking for sig_atomic_t in signal.h... yes
checking size of char... Segmentation fault (core dumped)
configure: error: in `/usr/ports/shells/bash/work/bash-4.4':
configure: error: cannot compute sizeof (char)
See `config.log' for more details
===>  Script "configure" failed unexpectedly.
Please report the problem to ehaupt@FreeBSD.org [maintainer] and attach the
"/usr/ports/shells/bash/work/bash-4.4/config.log" including the output of the
failure of your make command. Also, it might be a good idea to provide an
overview of all packages installed on your system (e.g. a
/usr/local/sbin/pkg-static info -g -Ea).
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/shells/bash`

**Comment by lattera** [comment]
Closing this as this issue is in the ports tree.
