### ISSUE TITLE
Compile Perl5.24 with safestac.

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedBSD#275]
Hello,

I have been trying to install Perl5.24 from ports for few days. I have never be able to do it. Im always getting this error:

> --- lib/buildcustomize.pl ---
> cc -lpthread -Wl,-E  -fstack-protector-strong -L/usr/local/lib -o miniperl  mpdtrace/opmini.o mpdtrace/perlmini.o mpdtrace/gv.o mpdtrace/toke.o mpdtrace/perly.o mpdtrace/pad.o mpdtrace/regcomp.o mpdtrace/dump.o mpdtrace/util.o mpdtrace/mg.o mpdtrace/reentr.o mpdtrace/mro_core.o mpdtrace/keywords.o mpdtrace/hv.o mpdtrace/av.o mpdtrace/run.o mpdtrace/pp_hot.o mpdtrace/sv.o mpdtrace/pp.o mpdtrace/scope.o mpdtrace/pp_ctl.o mpdtrace/pp_sys.o mpdtrace/doop.o mpdtrace/doio.o mpdtrace/regexec.o mpdtrace/utf8.o mpdtrace/taint.o mpdtrace/deb.o mpdtrace/universal.o mpdtrace/globals.o mpdtrace/perlio.o mpdtrace/perlapi.o mpdtrace/numeric.o mpdtrace/mathoms.o mpdtrace/locale.o mpdtrace/pp_pack.o mpdtrace/pp_sort.o mpdtrace/caretx.o mpdtrace/dquote.o mpdtrace/time64.o mpdtrace/miniperlmain.o dtrace_mini.o -lpthread -lm -lcrypt -lutil
> mpdtrace/opmini.o: In function `Perl_op_clear':
> opmini.c:(.text+0xb2a): undefined reference to `__safestack_unsafe_stack_ptr'
> opmini.c:(.text+0xddf): undefined reference to `__safestack_unsafe_stack_ptr'
> mpdtrace/opmini.o: In function `Perl_custom_op_get_field':
> opmini.c:(.text+0x16ed): undefined reference to `__safestack_unsafe_stack_ptr'
> opmini.c:(.text+0x1989): undefined reference to `__safestack_unsafe_stack_ptr'
> mpdtrace/opmini.o: In function `Perl_load_module':
> opmini.c:(.text+0x4e6b): undefined reference to `__safestack_unsafe_stack_ptr'
> mpdtrace/opmini.o:opmini.c:(.text+0x4f7d): more undefined references to `__safestack_unsafe_stack_ptr' follow
> cc: error: linker command failed with exit code 1 (use -v to see invocation)
> *** [lib/buildcustomize.pl] Error code 1
> 
> make[2]: stopped in /usr/ports/hbsd/lang/perl5.24/work/perl-5.24.2
> 1 error
> 
> make[2]: stopped in /usr/ports/hbsd/lang/perl5.24/work/perl-5.24.2
> ===> Compilation failed unexpectedly.
> Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
> the maintainer.
> *** Error code 1
> 
> Stop.
> make[1]: stopped in /usr/ports/hbsd/lang/perl5.24
> *** Error code 1
> 
> Stop.
> make: stopped in /usr/ports/hbsd/lang/perl5.24
> root@proton:/usr/ports/hbsd/lang/perl5.24 # 
> 

Some can help me to resolve it ?

Greetz,

**Comment by lattera** [comment]
This report should be over in the hardenedbsd-ports repo. I'll take a look at this issue soon.

Are you compiling lang/perl5.24 or any of its dependencies with custom options?

**Comment by bryn1u** [comment]
I have added only safestack option in "make config" then make install clean. Ports are downloaded from github.

**Comment by lattera** [comment]
Gotcha. So you'll probably not want to enable SafeStack for that port, then. ;)

**Comment by bryn1u** [comment]
I want to enable and i want to compile everything with safestack. But when i set safestack enable, perl is going to crash the same with bash.

**Comment by lattera** [comment]
SafeStack isn't ready to be enabled everywhere. So if you enable it, and something breaks, you'll need to disable it.
