### ISSUE TITLE
I'm having trouble finding the full fingerprint of the GPG key that the releases are signed with on the website

### ISSUE THREAD

**Issue by jmfgdev** [HardenedBSD/hardenedBSD#276]
My issue is that i want to run hardenedbsd, but the releases are signed with .asc files which are fetched over http and I can't seem to find the full fingerprint of the GPG key I should expect on the https site hardenedbsd.org.

To proceed installing I would need, a reliable place to check the full gpg key id.

It would also be nice if the downloads could be served over https in the future

**Comment by opntr** [comment]
I hope this helps: https://github.com/HardenedBSD/pubkeys

**Comment by jmfgdev** [comment]
I'm not finding the key "6FFD188D" in that repo, I need this key to verify the CHECKSUMS.SHA512 file

**Comment by jmfgdev** [comment]
The key I needed was dev@hardenedbsd.org, is this the correct fingerprint?
BB53 388D 3BD9 8928 15CB  9E30 819B 11A2 6FFD 188D

**Comment by lattera** [comment]
The `BB53 388D 3BD9 8928 15CB 9E30 819B 11A2 6FFD 188D` key is the correct key. This can also be verified by looking at [this](https://github.com/HardenedBSD/nyi01-tools/blob/master/jenkins/002-release-stable.zsh#L97) script.
