### ISSUE TITLE
Import HexVASAN

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#278]
HexVASAN is a sanitizer module that is complementary to CFI. It helps strengthen llvm's CFI implementation with regards to variadic functions.

HexVASAN can be found here: https://github.com/HexHive/HexVASAN

**Comment by opntr** [comment]
tl;dr: A very big NACK!

I don't want to see any third party compiler plugin in HardenedBSD's source tree. Until this project isn't part of the official LLVM suit, my answer will be NACK.
From other side, sanitizers aren't security countermeasures, they are only development tools, whose try to enlighten to find bugs in your code. And from this view, they are more like a security holes, than a mitigations, so from this reason too: NACK. 
For N+1th reason: the HexVASAN is lacks the license -> NACK.
