### ISSUE TITLE
secadm kmod doesn't follow up HardenedBSD 11-STABLE updates

### ISSUE THREAD

**Issue by carlopmart** [HardenedBSD/hardenedBSD#282]
After August 18th, update package for HardenedBSD 11-STABLE has problems with secadm kmod package.

Updating to latest
11.1-STABLE-HBSD FreeBSD 11.1-STABLE-HBSD #0 : Fri Sep 22 16:19:13 UTC 2017     root@updater-01:/usr/obj/usr/src/sys/HARDENEDBSD  amd64, components that needs secadm kmod like bhyve fails to start:

[24] tap6: promiscuous mode enabled
[24] pid 54848 (grub-bhyve), uid 0: exited on signal 11
[24] bridge0: link state changed to UP

Kernel's dmesg:

[2670] link_elf_obj: symbol pax_elf__FBSD_KPI1101503__HBSD_KPI1100049UL undefined
[2670] linker_load_file: Unsupported file type

**Comment by lattera** [comment]
This is due to secadm living outside the src tree. You will need to update your /usr/src to match the installed world/kernel and reinstall secadm from ports (not from pkg).

**Comment by opntr** [comment]
Please open the same ticket in HardenedBSD-ports git repo.

**Comment by carlopmart** [comment]
Done: [https://github.com/HardenedBSD/hardenedbsd-ports/issues/108](url)
