### ISSUE TITLE
GELI with ZFS on root causes redundant password prompt

### ISSUE THREAD

**Issue by lainy** [HardenedBSD/hardenedBSD#285]
After installation with ZFS on root using GELI, you will be prompted for the GELI passphrase twice: once during the bootloader, and again during mount root.

The cause is the installer script (unmodified from upstream FreeBSD) adds `geom_eli_load="YES"` to loader.conf when installing with GELI+ZFS, but HardenedBSD already compiles GELI into the kernel. Apparently, trying to load geom_eli when it is already present in the kernel somehow causes the double passphrase prompt.

Removing `geom_eli_load="YES"` from loader.conf fixes the issue.

**Comment by opntr** [comment]
The above patch committed into upstream, and pulled in into HardenedBSD. 328e5ffed1a056f76c9a377fc7e02d66171e004e
