### ISSUE TITLE
linker command failed

### ISSUE THREAD

**Issue by Cavadus** [HardenedBSD/hardenedBSD#288]
Currently working with the following script straight off FreeBSD's website:

`#include <sys/types.h>
#include <err.h>
#include <libgpio.h>

int main() {
  gpio_handle_t handle;

  handle = gpio_open(0);
  if(handle	== GPIO_INVALID_HANDLE)
    err(1, "gpio_open failed");
  gpio_pin_output(handle, 36);
  gpio_pin_high(handle, 36);
  gpio_close(handle);
  return 0;
}`

When I run this with clang I get the following error:

> /tmp/gpio_test-385c71.o: In function `main':
> gpio_test.c:(.text+0x12): undefined reference to `gpio_open'
> gpio_test.c:(.text+0x42): undefined reference to `gpio_pin_output'
> gpio_test.c:(.text+0x52): undefined reference to `gpio_pin_high'
> gpio_test.c:(.text+0x5d): undefined reference to `gpio_close'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

And the more verbose stacktrace:
>FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
> Target: x86_64-unknown-freebsd11.0
> Thread model: posix
> InstalledDir: /usr/bin
>  "/usr/bin/clang" -cc1 -triple x86_64-unknown-freebsd11.0 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name gpio_test.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -v -dwarf-column-info -debugger-tuning=gdb -resource-dir /usr/bin/../lib/clang/3.8.0 -fdebug-compilation-dir /root -ferror-limit 19 -fmessage-length 175 -fobjc-runtime=gnustep -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/gpio_test-ee2f5d.o -x c gpio_test.c
> clang -cc1 version 3.8.0 based upon LLVM 3.8.0 default target x86_64-unknown-freebsd11.0
> #include "..." search starts here:
> #include <...> search starts here:
>  /usr/bin/../lib/clang/3.8.0/include
>  /usr/include
> End of search list.
>  "/usr/bin/ld" --eh-frame-hdr -dynamic-linker /libexec/ld-elf.so.1 --hash-style=both --enable-new-dtags -o a.out /usr/lib/crt1.o /usr/lib/crti.o /usr/lib/crtbegin.o -L/usr/lib /tmp/gpio_test-ee2f5d.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/crtend.o /usr/lib/crtn.o
> /tmp/gpio_test-ee2f5d.o: In function `main':
> gpio_test.c:(.text+0x12): undefined reference to `gpio_open'
> gpio_test.c:(.text+0x42): undefined reference to `gpio_pin_output'
> gpio_test.c:(.text+0x52): undefined reference to `gpio_pin_high'
> gpio_test.c:(.text+0x5d): undefined reference to `gpio_close'

I'm not a C dev at all and no one else in my shop is either but I'm the one who was tasked with working through this.

**Comment by opntr** [comment]
Could you please put here your Makefile too?
