### ISSUE TITLE
MariaDB high CPU usage

### ISSUE THREAD

**Issue by gfvh** [HardenedBSD/hardenedBSD#294]
Hi

Having blocking issue after last hbsd-update 11.1 stable. i was already within 11.1
Production system.

CPU usage high and looking with truss i see that mariadb loops

env:

FreeBSD new 11.1-STABLE-HBSD FreeBSD 11.1-STABLE-HBSD #0 : Wed Dec 27 19:36:07 UTC 2017     root@updater-01:/usr/obj/usr/src/sys/HARDENEDBSD  amd64

mysql  Ver 15.1 Distrib 10.2.11-MariaDB, for FreeBSD11.1 (amd64) using readline 5.1

loops:

PID USERNAME    THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
43061     88       37  24    0  4841M   441M select 10   5:14 299.27% mysqld

truss -p 45018
``
_umtx_op(0x4bde9b2d2a8,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x62e012846718) = 0 (0x0)
_umtx_op(0x4bf1347ccb8,UMTX_OP_NWAKE_PRIVATE,0x1,0x0,0x0) = 0 (0x0)
_umtx_op(0x4bde9b2d2c0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x62e012645718) = 0 (0x0)
_umtx_op(0x4bf0213edb8,UMTX_OP_NWAKE_PRIVATE,0x1,0x0,0x0) = 0 (0x0)
_umtx_op(0x4bde9b2d2d8,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x62e012444718) = 0 (0x0)
sched_yield()					 = 0 (0x0)
_umtx_op(0x4bf1347c2b8,UMTX_OP_NWAKE_PRIVATE,0x1,0x0,0x0) = 0 (0x0)
_umtx_op(0x4bde9b2d290,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x62e012a47718) = 0 (0x0)
_umtx_op(0x4bf08b1dc60,UMTX_OP_MUTEX_WAIT,0x0,0x0,0x0) = 0 (0x0)
_umtx_op(0x4bf1347ccb8,UMTX_OP_NWAKE_PRIVATE,0x1,0x0,0x0) = 0 (0x0)
_umtx_op(0x4bde9b2d2a8,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x62e012846718) = 0 (0x0)
_umtx_op(0x4bf1347c7b8,UMTX_OP_NWAKE_PRIVATE,0x1,0x0,0x0) = 0 (0x0)
_umtx_op(0x4bde9b2d2d8,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x62e012444718) = 0 (0x0)
_umtx_op(0x4bf0213edb8,UMTX_OP_NWAKE_PRIVATE,0x1,0x0,0x0) = 0 (0x0)
``

**Comment by gfvh** [comment]
I consulted at maria irc channel. 

https://jira.mariadb.org/browse/MDEV-9784

seems to have same issue but closed without solution. i have also encryption turned on and innodb only.
conf here https://dpaste.de/puT0/raw

also i recompiled from /usr/ports/databases/mariadb102-server with make install clean

and built pkg -s

pkg install unixODBC-2.3.4.txz libiconv-1.14_11.txz libedit-3.1.20170329_2,1.txz mariadb102-client-10.2.11.txz libxml2-2.9.7.txz libuv-1.18.0.txz libunistring-0.9.7.txz libidn2-2.0.4.txz libarchive-3.3.2,1.txz gettext-runtime-0.19.8.1_1.txz expat-2.2.1.txz dialog4ports-0.1.6.txz lzo2-2.10_1.txz readline-7.0.3_1.txz rhash-1.3.5.txz unixODBC-2.3.4.txz m4-1.4.18,1.txz mariadb102-server-10.2.11_1.txz

this leads me to weird pid not found issue while i can do touch to pid and with retry service mysql-server start again no pid file

debugging:

truss shows all fine result until to pid file issue and it does maky any sense since /usr/local/etc/my.cnf is there and configure is correct. datadir exists

15824: close(45)                                 ERR#9 'Bad file descriptor'
15824: close(46)                                 ERR#9 'Bad file descriptor'
15824: close(47)                                 ERR#9 'Bad file descriptor'
15824: close(48)                                 ERR#9 'Bad file descriptor'
15824: close(49)                                 ERR#9 'Bad file descriptor'
15824: close(50)                                 ERR#9 'Bad file descriptor'
15824: close(51)                                 ERR#9 'Bad file descriptor'
15824: close(52)                                 ERR#9 'Bad file descriptor'
15824: close(53)                                 ERR#9 'Bad file descriptor'
15824: close(54)                                 ERR#9 'Bad file descriptor'
15824: close(55)                                 ERR#9 'Bad file descriptor'
15824: close(56)                                 ERR#9 'Bad file descriptor'
15824: close(57)                                 ERR#9 'Bad file descriptor'
15824: close(58)                                 ERR#9 'Bad file descriptor'
15824: close(59)                                 ERR#9 'Bad file descriptor'
15824: close(60)                                 ERR#9 'Bad file descriptor'
15824: close(61)                                 ERR#9 'Bad file descriptor'
15824: close(62)                                 ERR#9 'Bad file descriptor'
15824: close(63)                                 ERR#9 'Bad file descriptor'
----

80109: read(11,"junk < $_pidfile\n\tif [ -z "$_p"...,1024) = 1024 (0x400)
20843: getpid()                                  = 20843 (0x516b)
20843: getpid()                                  = 20843 (0x516b)
80109: getpid()                                  = 80109 (0x138ed)
80109: getpid()                                  = 80109 (0x138ed)
80109: getpid()                                  = 80109 (0x138ed)
80109: getpid()                                  = 80109 (0x138ed)
80109: getpid()                                  = 80109 (0x138ed)
80109: getppid()                                 = 27065 (0x69b9)
80109: read(11,"junk < $_pidfile\n\tif [ -z "$_p"...,1024) = 1024 (0x400)
53049: getpid()                                  = 53049 (0xcf39)
53049: getpid()                                  = 53049 (0xcf39)
80109: read(10,"ql_pidfile="\\${mysql_${instance"...,1024) = 1024 (0x400)
63633: getpid()                                  = 63633 (0xf891)
63633: getpid()                                  = 63633 (0xf891)
79676: getpid()                                  = 79676 (0x1373c)
79676: getpid()                                  = 79676 (0x1373c)
24832: stat("/var/db/mysql/sqlprod.pid",0x402a1200040) ERR#2 'No such file or directory'

**Comment by gfvh** [comment]
I also tried given jira suggestion innodb-encryption-rotate-key-age = 0
Seems to help but this means that some parts are now less encrypted

Dropped to zero cpu usage. All normal now in terms of io. And yes i did reinstall as bin pkg from repo

Should i close this?

**Comment by lattera** [comment]
I'll go ahead and close this, then. It seems from the bug report you referenced and your own comments that the bug lies within MariaDB.

Another option for database encryption would be to place the database files on a geli-encrypted volume.
