### ISSUE TITLE
rspamd: update to 1.7.2

### ISSUE THREAD

**Issue by heraklit256** [HardenedBSD/hardenedBSD#298]
Hello,

HardenedBSD currently ships rspamd 1.6.6, which is outdated (current version is 1.7.2).
I was not sure where to report this exactly, some commits related to rspamd appeared in graphic-ports, but that repository seems to be orphaned, so I just write that down here.

Please correct me if that was the wrong part.

Thank you very much.

**Comment by opntr** [comment]
Hi!

This is wrong place for ports related issues. Please reopen them in HardenedBSD/hardenedbsd-ports git repo.
