### ISSUE TITLE
Unable to properly disable hardening features for binary through file extended attributes.

### ISSUE THREAD

**Issue by dmilith** [HardenedBSD/hardenedBSD#304]
I'm trying to use file attributes like on example here: http://ix.io/17Ps

System: 11.2-PRERELEASE

Pre:

My default /etc/sysctl.conf:

```
…
hardening.pax.segvguard.status: 3
hardening.pax.mprotect.status: 3
hardening.pax.pageexec.status: 3
hardening.pax.disallow_map32bit.status: 3
hardening.pax.aslr.status: 3
```

Applying overrides for specific software:

```
sh ${HBSDCTRL} system segvguard disable /Software/Node/bin/node
sh ${HBSDCTRL} system mprotect disable /Software/Node/bin/node
sh ${HBSDCTRL} system pageexec disable /Software/Node/bin/node
sh ${HBSDCTRL} system aslr disable /Software/Node/bin/node
sh ${HBSDCTRL} system disallow_map32bit disable /Software/Node/bin/node
```

Then trying to invoke this software, results with message from kernel:
http://s.verknowsys.com/0a63faa6bb3133b99052c4e35643286f.png

In short this means that only NOSEGVGUARD and NODISALLOWMAP32BIT work. Other features are in "hardened" mode (3) until I will set `hardening.pax.*.status: 1` for each feature respectively. Otherwise features are still enforced, which makes Node segfault:

```
λ /Software/Node/bin/node
zsh: segmentation fault  /Software/Node/bin/node
```

Just for clearance, exports/node is only a symlink to binary: 

```
λ ls -la `which node`
lrwxr-xr-x  1 root  wheel  11 Jun  2 22:54 /Software/Node/exports/node@ -> ../bin/node
```

**Comment by dmilith** [comment]
Of course it works when I disable all features via sysctl: http://s.verknowsys.com/41b7b6a571483f20aa25ffa0359ae350.png

**Comment by opntr** [comment]
Hi!

Works as intended. Value 3 in sysctl means forced on, and you can't disable
the feature with hbsdcontrol nor secadm.

The whole table is in hardening man page or bellow:

0: force off, you can't enable them via control toola
1: opt-in, default off, but you can enable them via control toola
2: opt-out, default on, you can disable them
3: force on, always on, you can't disable them

**Comment by dmilith** [comment]
Hmm. Why then I can override only forced disallow_map32bit and segvguard values? :)

Thanks for information. I didn't know that force means "you can't override it via xattrs". <3 !

**Comment by opntr** [comment]
Could you please show me the full sysctl.conf, loader.conf and a sysctl
hardening. output?

**Comment by dmilith** [comment]
/boot/loader.conf: 
```
kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
zfs_load="YES"
```

/boot/loader.conf.local:
```
loader_logo="beastie"
autoboot_delay="2"

cc_htcp_load="YES"
accf_http_load="YES"
dtrace_load="YES"
vmm_load="YES"
nullfs_load="YES"

net.link.ifqmaxlen="2048"
net.inet.tcp.syncache.hashsize=32768
net.inet.tcp.syncache.bucketlimit=32
net.inet.tcp.syncache.cachelimit=1048576
kern.ipc.maxsockets=204800
kern.ipc.nmbclusters=262144
hw.em.rxd=4096
hw.em.txd=4096
hw.em.rx_process_limit="-1"
hw.igb.rxd=4096
hw.igb.txd=4096
hw.igb.rx_process_limit=100
kern.maxusers=2048
net.fibs=16

kern.ipc.semmap=512
kern.ipc.shmseg=64
kern.ipc.shmmni=16384
kern.ipc.shmall=33554432
kern.ipc.shmmax=68719476736
kern.ipc.semmni=4096
kern.ipc.semmns=8194
kern.ipc.semmnu=4096
```

Current sysctl hardening:

```
hardening.procfs_harden: 1
hardening.log.ulog: 0
hardening.log.log: 1
hardening.version: 1100055
hardening.control.extattr.status: 1
hardening.control.acl.status: 1
hardening.pax.segvguard.max_crashes: 5
hardening.pax.segvguard.suspend_timeout: 600
hardening.pax.segvguard.expiry_timeout: 120
hardening.pax.segvguard.status: 2
hardening.pax.mprotect.status: 2
hardening.pax.pageexec.status: 2
hardening.pax.disallow_map32bit.status: 2
hardening.pax.aslr.status: 2
```

I double-checked all that. It works as expected with not forced hardening settings. Thanks!

**Comment by dmilith** [comment]
```sysctl -d hardening.pax.disallow_map32bit.status
hardening.pax.disallow_map32bit.status: Restrictions status: 0 - disabled, 1 - opt-in,  2 - opt-out, 3 - force enabled```

Maybe it could be "force enabled (no extended attributes override possible)" :)?
