### ISSUE TITLE
hbsd-update failed: tar: Error exit delayed from previous errors.

### ISSUE THREAD

**Issue by heraklit256** [HardenedBSD/hardenedBSD#312]
Updating to current version of HardenedBSD fails:

    root@[redacted]:~ # hbsd-update -V
    [*] Latest build: hbsd-v1100055-5338c38a00d868e651fb23f0d7fa43c6d577f14f
    /tmp/tmp.mp8eLgzM/update.tar                  100% of  300 MB   10 MBps 00m28s
    [*] Verified hash: 71f8786c27be01ab2d3504a4d56526ef98ea8836af2025cae6d82bc276c86d8f = 71f8786c27be01ab2d3504a4d56526ef98ea8836af2025cae6d82bc276c86d8f
    [*] Checking validity of the public key
    [*] Checking the validity of base.txz
    [*] Checking the validity of etcupdate.tbz
    [*] Checking the validity of skip.txt
    [*] Checking the validity of kernel-HARDENEDBSD.txz
    [*] Checking the validity of ObsoleteFiles.txt
    [*] Checking the validity of ObsoleteDirs.txt
    [*] Checking the validity of script.sh
    [*] Checking the validity of secadm.integriforce.rules
    ******************
    * IMPORTANT NOTE *
    ******************
    
    This update includes the PTI patch. Third-party kernel modules (such
    as x11/nvidia-driver and hardenedbsd/secadm-kmod) will need to be
    recompiled/reinstalled.

    If you wish to postpone installing this update, please hit Control-C
    within the next ten (10) seconds.
    [*] Applying base
    ./usr/libexec/dwatch/proc-status: Hard-link target './usr/libexec/dwatch/proc' does not exist.
    ./usr/libexec/dwatch/proc-exec: Hard-link target './usr/libexec/dwatch/proc' does not exist.
    ./usr/libexec/dwatch/proc-signal: Hard-link target './usr/libexec/dwatch/proc' does not exist.
    ./usr/libexec/dwatch/proc-signal-send: Hard-link target './usr/libexec/dwatch/proc' does not exist.
    ./usr/libexec/dwatch/proc-signal-clear: Hard-link target './usr/libexec/dwatch/proc' does not exist.
    ./usr/libexec/dwatch/proc-signal-discard: Hard-link target './usr/libexec/dwatch/proc' does not exist.
    ./usr/libexec/dwatch/proc-exec-failure: Hard-link target './usr/libexec/dwatch/proc' does not exist.
    ./usr/libexec/dwatch/proc-exit: Hard-link target './usr/libexec/dwatch/proc' does not exist.
    ./usr/libexec/dwatch/proc-create: Hard-link target './usr/libexec/dwatch/proc' does not exist.
    ./usr/libexec/dwatch/proc-exec-success: Hard-link target './usr/libexec/dwatch/proc' does not exist.
    tar: Error exit delayed from previous errors.

This seems to be reproducable. Output of `uname -a`:

    FreeBSD [redacted] 11.2-PRERELEASE-HBSD FreeBSD 11.2-PRERELEASE-HBSD #0 : Thu Jun 14 03:31:14 UTC 2018     root@updater-01:/usr/obj/usr/src/sys/HARDENEDBSD  amd64

**Comment by wodev** [comment]
Same issue on my hardenedbsd 11 Machine:

`root@hbsd01:~ #	hbsd-update -V -C
[+] Local version: hbsd-v1100055-e2d9d5dc06dfbeb97d2c62fbce0acd90badd2854
[+] Remote version: hbsd-v1100055-5338c38a00d868e651fb23f0d7fa43c6d577f14f sha256 71f8786c27be01ab2d3504a4d56526ef98ea8836af2025cae6d82bc276c86d8f
root@hbsd01:~ #	hbsd-update -V
[*] Latest build: hbsd-v1100055-5338c38a00d868e651fb23f0d7fa43c6d577f14f
/tmp/tmp.5JEP20As/update.tar                  100% of  300 MB 2828 kBps 01m49s
[*] Verified hash: 71f8786c27be01ab2d3504a4d56526ef98ea8836af2025cae6d82bc276c86d8f = 71f8786c27be01ab2d3504a4d56526ef98ea8836af2025cae6d82bc276c86d8f
[*] Checking validity of the public key
[*] Checking the validity of base.txz
[*] Checking the validity of etcupdate.tbz
[*] Checking the validity of skip.txt
[*] Checking the validity of kernel-HARDENEDBSD.txz
[*] Checking the validity of ObsoleteFiles.txt
[*] Checking the validity of ObsoleteDirs.txt
[*] Checking the validity of script.sh
[*] Checking the validity of secadm.integriforce.rules
******************
* IMPORTANT NOTE *
******************

This update includes the PTI patch. Third-party kernel modules (such
as x11/nvidia-driver and hardenedbsd/secadm-kmod) will need to be
recompiled/reinstalled.

If you wish to postpone installing this update, please hit Control-C
within the next ten (10) seconds.
[*] Applying base
./usr/libexec/dwatch/proc-status: Hard-link target './usr/libexec/dwatch/proc' does not exist.
./usr/libexec/dwatch/proc-exec: Hard-link target './usr/libexec/dwatch/proc' does not exist.
./usr/libexec/dwatch/proc-signal: Hard-link target './usr/libexec/dwatch/proc' does not exist.
./usr/libexec/dwatch/proc-signal-send: Hard-link target './usr/libexec/dwatch/proc' does not exist.
./usr/libexec/dwatch/proc-signal-clear: Hard-link target './usr/libexec/dwatch/proc' does not exist.
./usr/libexec/dwatch/proc-signal-discard: Hard-link target './usr/libexec/dwatch/proc' does not exist.
./usr/libexec/dwatch/proc-exec-failure: Hard-link target './usr/libexec/dwatch/proc' does not exist.
./usr/libexec/dwatch/proc-exit: Hard-link target './usr/libexec/dwatch/proc' does not exist.
./usr/libexec/dwatch/proc-create: Hard-link target './usr/libexec/dwatch/proc' does not exist.
./usr/libexec/dwatch/proc-exec-success: Hard-link target './usr/libexec/dwatch/proc' does not exist.
tar: Error exit delayed from previous errors.
root@hbsd01:~ #`

`root@hbsd01:~ #	uname -a
FreeBSD hbsd01 11.2-PRERELEASE-HBSD FreeBSD 11.2-PRERELEASE-HBSD #0 : Thu Jun 14 03:31:14 UTC 2018     root@updater-01:/usr/obj/usr/src/sys/HARDENEDBSD  amd64
root@hbsd01:~ #`

HardenedBSD is virtualised with KVM.

**Comment by wodev** [comment]
Now update to HardenedBSD-11-STABLE-v1100056 was successful :-)

**Comment by heraklit256** [comment]
Here too. Closing this issue although there was no technical solution.
