### ISSUE TITLE
buildworld WITHOUT_CRYPT breaks at libldns

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [HardenedBSD/hardenedBSD#321]
I use WITHOUT_CRYPT for minimal world/kernel build time, and install SSL from packages. Setting now causes problem at LDNS_UTILS build stage.

===> lib/libldns (all)
Building .../lib/libldns/buffer.o
In file included from .../src/contrib/ldns/buffer.c:12:
In file included from .../src/contrib/ldns/ldns/ldns.h:98:
.../src/contrib/ldns/ldns/dane.h:30:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>

Regards.

**Comment by Beeblebrox-BSD** [comment]
There's something else going on here, perhaps the git repo has problems? Same problem after doing all of below.
* Unset WITHOUT_CRYPT
* Cleaned out files in MAKEOBJDIRPREFIX
* Deleted local cloned repo and re-cloned with
git clone --depth 1 --branch hardened/current/master https://github.com/HardenedBSD/hardenedBSD.git

**Comment by opntr** [comment]
I  categorized this bug as invalid, because libldns requires openssl.
This is a base system utility, which are not permitted to link for ports openssl.

**Comment by opntr** [comment]
Once solution would be to disable the building of the libldns, when the WITHOUT_CRYPT is specified, but this would be better to solve in FreeBSD (our upstream).
