### ISSUE TITLE
Implement updates via Tor

### ISSUE THREAD

**Issue by heraklit256** [HardenedBSD/hardenedBSD#328]
In Debian, there is `apt-transport-tor` to fetch updates and packages in general via anonymously via Tor.
(There even is a hidden service mirror, see https://onion.debian.org/ .)

Having this possbility in HardenedBSD, too (for both `hbsd-update` and `pkg`) would be a great feature so passive attackers cannot determine OS details just by looking at package or update traffic.

**Comment by lattera** [comment]
Hey there! We already support updating via Tor: https://hardenedbsd.org/article/shawn-webb/2017-03-11/hardenedbsd-through-tor-hidden-service

I myself use our Tor onion services just about every day. :)

I'm going to close this ticket out, but if you have any further questions, comments, or concerns, please feel free to re-open.

**Comment by heraklit256** [comment]
I was unaware of this article. Thanks very much.

**Comment by lattera** [comment]
No worries. We don't guarantee the availability of the onion service. Only rarely does it go down.
