### ISSUE TITLE
confusion about HBSD version on website

### ISSUE THREAD

**Issue by heraklit256** [HardenedBSD/hardenedBSD#330]
Not sure if this is the right place for it.

On https://hardenedbsd.org/content/easy-feature-comparison , it says that some of the security features are implemented in `12-CURRENT/amd64` only. However, I was unable to find version 12 of HBSD anywhere. Is this a typo?

Thanks very much.

**Comment by opntr** [comment]
Hi!

About the website you should directly send an e-mail to core@hardenedbsd.org or to shawn.

From the other side, you can reach the 12-CURRENT installers on jenkins.hardenedbsd.org site.
