### ISSUE TITLE
secadm feature request: Reload

### ISSUE THREAD

**Issue by utrenkner** [HardenedBSD/hardenedBSD#345]
Not at all a priority, but on *my* wish list for secadm are:

- ``secadm reload``: flush and reload rules file
- ``secadm load`` without a file parameter to load existing rules files from the default location (/usr/local/etc/secadm.rules); this location is already used as default for ``secadm_enable="YES"`` in /etc/rc.conf.

Again: Just a suggestion... Thanks!

**Comment by lattera** [comment]
Thank you for reporting this. `secadm` doesn't exist in base, yet. Can you close this ticket and reopen at this repo: https://github.com/hardenedbsd/secadm

Thanks!

**Comment by utrenkner** [comment]
Sorry. You are, of course, absolutely right. I just re-created this issue over at the secadm repo.
