### ISSUE TITLE
hbsd-update fails on "-D -t" option

### ISSUE THREAD

**Issue by utrenkner** [HardenedBSD/hardenedBSD#348]
Today, I updated the host with
```
hbsd-update -t /tmp/update_2018-09-30 -T 
```
I then proceeded to update the iocage base jail re-using the downloaded update.tar:
```
hbsd-update -n -D -t /tmp/update_2018-09-30 -r /iocage/releases/11-STABLE/root
```
The update of the jail failed with the following message:
```
mkdir: /tmp/update_2018-09-30/mtree: File exists
```
This procedure has worked in the past, so the problem must have been newly entered hbsd-update.

**Comment by lattera** [comment]
I fixed this with commit e6ba4e63901673cd6f702364316cfabd27ff77c9. I just barely MFC'd it to 11-STABLE. The fix will be in the next 11-STABLE update.
