### ISSUE TITLE
hbsd-update fails but DNS record is available

### ISSUE THREAD

**Issue by heraklit256** [HardenedBSD/hardenedBSD#351]
I am observing an interesting behaviour on a HardenedBSD machine located behind some DNS proxies. `hbsd-update` fails with a DNS(SEC) error:
```
[*] Looking up version info with DNSSEC enabled.
[-] Could not get DNS record.
    [-] Bailing.
[*] Could not get the version number
[*] Raw DNS result:
Host amd64.master.11-stable.hardened.hardenedbsd.updates.hardenedbsd.org not found: 2(SERVFAIL). (insecure)
```

However, DNS and even DNSSEC work correctly. Further, there is no trouble looking up the given hostname by using `dig`:
```
[root@machine ~]# dig txt amd64.master.11-stable.hardened.hardenedbsd.updates.hardenedbsd.org

; <<>> DiG 9.12.2-P1 <<>> txt amd64.master.11-stable.hardened.hardenedbsd.updates.hardenedbsd.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12463
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;amd64.master.11-stable.hardened.hardenedbsd.updates.hardenedbsd.org. IN	TXT

;; ANSWER SECTION:
amd64.master.11-stable.hardened.hardenedbsd.updates.hardenedbsd.org. 3600 IN TXT "1538087408|hbsd-v1100056-b9ec89b43b498e3bc45d3aaa4e14fb979494e5a9|sha256:fca3975a64ed31034580b0c41eb1046997f51fbe3a6b6ad5f8e812412a12e6f0"

;; Query time: 33 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Oct 11 11:52:31 CEST 2018
;; MSG SIZE  rcvd: 246
```

What am I doing wrong (using a local Unbound, but that should work and does in other scenarios as well)? Is this even a bug?

Thanks very much.

**Comment by lattera** [comment]
The `(insecure)` flag in the error message shows that DNSSEC is not working properly with your setup.

**Comment by heraklit256** [comment]
Does HardenedBSD require anything special in my DNSSEC setup?

I am pretty sure DNSSEC information is available - the `dig` output in my original post indicates successful validation (`ad`-flag). Since I am flying blind at the moment, any help is appreciated. :-)

**Comment by lattera** [comment]
`hbsd-update` uses `drill` in base as the resolver. You may need to provide extra configuration for it to properly perform lookups with DNSSEC enforced.

**Comment by heraklit256** [comment]
Thank you very much.

After some debugging, it turned out `${UNBOUND_HOST}` has to be called with `-r`option to make this work:
```
[root@machine ~]# /usr/sbin/unbound-host  -v -t txt -f /usr/share/keys/hbsd-update/trusted/dnssec.key amd64.master.11-stable.hardened.hardenedbsd.updates.hardenedbsd.org
Host amd64.master.11-stable.hardened.hardenedbsd.updates.hardenedbsd.org not found: 2(SERVFAIL). (insecure)
[root@machine ~]# /usr/sbin/unbound-host  -r -v -t txt -f /usr/share/keys/hbsd-update/trusted/dnssec.key amd64.master.11-stable.hardened.hardenedbsd.updates.hardenedbsd.org
amd64.master.11-stable.hardened.hardenedbsd.updates.hardenedbsd.org has TXT record "1539829783|hbsd-v1100056-f86e7a6d6d9a988cd68796a1ac70c6f629a09e86|sha256:39be9535227319c7f9876a934274dcd61d001f01828a094e1ed560bda04dac77" (secure)
```

According to its manpage, `-r` causes Unbound to use DNS servers specified in `/etc/resolv.conf`. What remains unclear to me is how to tell the script to use the local resolver.

**Comment by heraklit256** [comment]
After consulting the documentation (RTFM...), adding
```
local_resolver=1
```
to `/etc/hbsd-update.conf` solved the problem.

Thank you for the hints. Closing this issue...
