### ISSUE TITLE
cannot load secadm.ko - maybe because of a version mismatch on 13.0 CURRENT

### ISSUE THREAD

**Issue by pernila** [HardenedBSD/hardenedBSD#354]
Cannot load secadm.ko on 13.0 CURRENT

details from dmesg after kldload secadm.ko

KLD secadm.ko: depends on kernel - not available or version mismatch
linker_load_file: /boot/modules/secadm.ko - unsupported file type

 More info just if needed:
file /boot/modules/secadm.ko 
shows the it's the normal ELF 64bit binary 
with size of 50512

**Comment by lattera** [comment]
I believe this is because of a recent bump in `__FreeBSD_version` from upstream FreeBSD.

What's the output of `uname -K`?

**Comment by lattera** [comment]
Never mind. The `secadm-kmod` package failed to build. I'll have to take a look.

**Comment by pernila** [comment]
That makes sense :)

No wonder it wasn't working

-T

**Comment by lattera** [comment]
Closing this. The `secadm-kmod` package now builds on 13-CURRENT.
