### ISSUE TITLE
23:26 < emaste> speaking of which, would you mind extracting the -z now infrastructure and posting a patch?

### ISSUE THREAD

**Issue by opntr** [HardenedBSD/hardenedBSD#356]

**Comment by lattera** [comment]
@emaste, would you like me to include RELRO? In terms of security, BIND_NOW doesn't make much sense without RELRO.

**Comment by emaste** [comment]
Thanks - I'm just hoping to avoid gratuitous differences and conflicts if you've already done the work. Feel free to stick it on Phabricator or just make a branch in this repo and I can pluck it from there.

**Comment by lattera** [comment]
Closing this due to @emaste writing his own patch, as per discussion on IRC. Thanks for the productive and constructive conversation!
