### ISSUE TITLE
Ports errors on 12-STABLE

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [HardenedBSD/hardenedBSD#364]
A number of ports errors in one thread, I hope this is acceptable etiquette.
I also realise that several of these are from upstream.

1. ports-mgmt/pkg (1.10.5_5)
Fails to build if UNSET+=DOCS

2. ftp/curl (7.62.0) from HBSD repo pulls in openssl but requires openssl11
* assumes kerberos from base, does not pull in the heimdal. Even if heimdal is installed separately, curl still looks for krb5, which is incompatible with heimdal. The solution is to build with UNSET+=LIBSSH2

3. Several ports fail to build with pkg error:
package: 1200500,   kernel: 1200076
Failed to install package pkg-1.10.5_5.txz
Running HBSD kernel 12.0-STABLE 311ab7ac288. amd64
__HardenedBSD_version 1200058 __FreeBSD_version 1200501
Ports thus far failing with this error:
openjdk8
openjdk(7)
gstreamer-ffmpeg
gstreamer1-libav
ffmpeg

**Comment by opntr** [comment]
Wrong repo, please reopen the bug in the proper repository.
