### ISSUE TITLE
Creating a new jail on 11 with hbsd-update fails.

### ISSUE THREAD

**Issue by leper** [HardenedBSD/hardenedBSD#365]
When trying to create a new jail on 11 using `hbsd-update -n -r /path/to/newjaildir -D -t /tmp/foobar -d` fails with `[-] Could not find any applicable kernels`, which is odd given that `-n` is passed.

Not passing `-n` makes it succeed.

With the following diff the above commands succeed as expected.

```
--- a/usr/sbin/hbsd-update
+++ b/usr/sbin/hbsd-update
@@ -1168,11 +1168,13 @@
 		exit 0
 	fi
 
-	set_kernel_config
-	res=${?}
-	if [ ${res} -gt 0 ]; then
-		cleanup
-		exit 1
+	if [ ${no_kernel} -eq 0 ]; then
+		set_kernel_config
+		res=${?}
+		if [ ${res} -gt 0 ]; then
+			cleanup
+			exit 1
+		fi
 	fi
 
 	if [ ${unsigned} -eq 0 ]; then
```

**Comment by lattera** [comment]
Thanks for the report and for the patch! I'll leave this issue open until MFC is performed.

**Comment by lattera** [comment]
MFC has been completed. Thanks for the report and the patch!
