### ISSUE TITLE
Illegal instruction 12.0-STABLE-HBSD

### ISSUE THREAD

**Issue by o2b3** [HardenedBSD/hardenedBSD#371]
Hello! When i create NFS client/server and use follow commands "**rpcinfo**" "**showmount**" console output error "**Illegal instruction (core dumped)**". This error shown on 12.0 version. On 11.2 all work fine.

[Dumps](https://ufile.io/wu9hc)
# 12.0-STABLE-HBSD

**# cat /etc/rc.conf | tail -n4**
```
rpcbind_enable="YES"
mountd_enable="YES"
nfsd_enable="YES"
nfs_server_enable="YES"
```
**# rpcinfo -p**
`Illegal instruction (core dumped)`
**# showmount -e**
`Illegal instruction (core dumped)`

# 11.2-STABLE-HBSD

**# cat /etc/rc.conf | tail -n4**
```
rpcbind_enable="YES"
mountd_enable="YES"
nfsd_enable="YES"
nfs_server_enable="YES"
```
**# rpcinfo -p**
```
   program vers proto   port  service
    100000    4   tcp    111  rpcbind
    100000    3   tcp    111  rpcbind
    ...
```
**# showmount -e**
`Exports list on localhost:`

**Comment by lattera** [comment]
Closing this issue now that the fixes have been MFC'd and released.
