### ISSUE TITLE
starting secadm causes system crash in 12-STABLE v1200058.4

### ISSUE THREAD

**Issue by heraklit256** [HardenedBSD/hardenedBSD#375]
After upgrading to the latest version of HardenedBSD, one of my servers keeps crashing at boot time. It writes a dump to disk and reboots into an infinity loop.
```
[root@machine]# less /var/crash/info.last 
Dump header from device: /dev/da0s1b
  Architecture: amd64
  Architecture Version: 2
  Dump Length: 265912320
  Blocksize: 512
  Compression: none
  Dumptime: Fri Mar 29 08:58:09 2019
  Hostname: [redacted]
  Magic: FreeBSD Kernel Dump
  Version String: FreeBSD 12.0-STABLE-HBSD  HARDENEDBSD-12-STABLE
  Panic String: page fault
  Dump Parity: 1654441274
  Bounds: 0
  Dump Status: good
```
Since other systems are patched successfully so far, I guess it is rather an issue with a package (possible `secadm`) than with HardenedBSD in general - disabling `secadm` in `/etc/rc.conf` results in a clean boot again.

Please let me know which further information is helpful here. Thanks!

**Comment by heraklit256** [comment]
`secadm` causes this problem. After starting it via `service secadm onestart`, the same crash occurs and system is rebooting.

**Comment by murf0** [comment]
Have the exact same issue, Secadm panics the system. I dont have access to the system right now so no log. Using hbsd-update to update the system ran it just before the reboot yesterday that caused the panic.
Can also help if anything needs to be checked or tested.

**Comment by heraklit256** [comment]
Removing and reinstalling `secadm`, `secadm-kmod` (seems to be a depenancy of `secadm`, but needs to be installed manually) solves the problem here. After cleaning up some manually added rules (need them for `rspamd`) and rebooting the system, everything seems to be fine again.

The issue did not seem to be related to security levels, as it occurred both on -1 and 2.

**Comment by murf0** [comment]
Ah, Thanks I'll try and verify when i get a chance later today.

**Comment by lattera** [comment]
This kind of thing can be solved with `pkg clean -y && pkg upgrade -f secadm-kmod` once the 12-STABLE/amd64 (or 11-STABLE/amd64, if you use 11-STABLE) package repo is updated to reflect the latest release.

**Comment by lattera** [comment]
Is this still an issue or can this ticket be closed out?

**Comment by heraklit256** [comment]
Sorry for the late reply.

As far as I am concerned, this ticket can be closed. In case this kind of thing happens again, I know what the solution is. :-)
