### ISSUE TITLE
Import LibreSSL Into Base

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#43]
We should investigate whether we could replace base OpenSSL with LibreSSL.

**Comment by opntr** [comment]
ERESOURCE, our team is currently very small.

**Comment by opntr** [comment]
new round of work started by @Sp1l in https://github.com/HardenedBSD/hardenedBSD-playground/tree/hardened/current/libressl

**Comment by opntr** [comment]
FYI: @fichtner

**Comment by lattera** [comment]
Short-term goals:

- Import  LibreSSL into base such that OpenSSL and LibreSSL can co-exist.
- Add a WITH_LIBRESSL flag for src.conf(5) (when this flag is turned on, OpenSSL will not be used)

Long-term goals:
- Hopefully switch WITHOUT_OPENSSL to WITH_OPENSSL and WITH_LIBRESSL to WITHOUT_LIBRESSL (making LibreSSL the default)

**Comment by Sp1l** [comment]
Please stop bringing up the PID-wrap issue. Is the current OpenSSL PID-wrap safe? And then there's [this report](https://eprint.iacr.org/2016/367.pdf) as well
> Abstract. In this work we demonstrate various weaknesses of the random number generator (RNG) in the OpenSSL cryptographic library.

**Comment by xmj** [comment]
@Sp1l @lattera can this be closed, or should we wait until stable/11 gets libressl by default?

**Comment by lattera** [comment]
This should probably remain open until we can remove the special LibreSSL-flavored branches.

**Comment by opntr** [comment]
Libressl is now in hardened/11-stable/master an in hardened/current/master.
