### ISSUE TITLE
EPFL's Code-Pointer Integrity

### ISSUE THREAD

**Issue by opntr** [HardenedBSD/hardenedBSD#50]
Mentioned by Eitan Adler <eadler@freebsd.org>

http://dslab.epfl.ch/pubs/cpi.pdf
http://levee.epfl.ch/

**Comment by ndauten** [comment]
@opntr I have contacted the lead author on the CPI work and he is very excited and interested in putting his work into HardenedBSD.

His work is both a compiler modification and a set of modifications to some libraries. 

They have submitted the SafeStack support for consideration into FreeBSD, which has passed all requisite tests. Their patched FreeBSD repo is on github, all changes are in the latest 3 commits: https://github.com/cpi-llvm/freebsd/commits/safestack/head. 

I will discuss the best approach with them, but I think giving them a branch to port in their work would probably be fastest. They may need a few branches though, as they have a few variants. I will update when more information is acquired.

**Comment by opntr** [comment]
this merged to LLVM 3.7

**Comment by ndauten** [comment]
Oliver, I think there is still some patches that go directly into the
FreeBSD libraries. So I 'm not sure we want to close it.
