### ISSUE TITLE
getdtablecount()

### ISSUE THREAD

**Issue by reyk** [HardenedBSD/hardenedBSD#63]
FreeBSD does not support the getdtablecount() syscall which is used by OpenBSD's file descriptor accounting technique in various places.

The FreeBSD port of OpenBSD's relayd turns off file descriptor accounting which might cause unexpected behavior or even DoS under load.

See:
https://github.com/mmatuska/relayd/compare/OpenBSD...master#diff-178da6a5bcd99dd1e0718e12bb086d86R1057
https://github.com/mmatuska/relayd/compare/OpenBSD...master#diff-79d5dc26d480efbce03d84ba02cb8f38R72

The use of getdtablecount() is found in various subprojects of OpenBSD, for example relayd and httpd, and a usage example can also be found in the FreeBSD port of relayd:
https://github.com/mmatuska/relayd/blob/master/src/usr.sbin/relayd/relayd.c#L1673

See OpenBSD for more information:
http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man2/getdtablecount.2

Reyk

**Comment by bapt** [comment]
FYI there is imho no need for a new syscall on freebsd for this as we do have this information (somehow) available via sysctl or via a user kinfo_getfiles(3) available in libutil

**Comment by opntr-auto** [comment]
This patch exists only in unstable branch and never merged to master.

**Comment by opntr** [comment]
https://github.com/HardenedBSD/hardenedBSD/commit/bc4e60465f09836d24e92a50cb8e5273c32421d5
