### ISSUE TITLE
Support grub in bsdinstall

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#81]
This isn't a HardenedBSD-related issue per se, but grub can integrate with geli and can work with UEFI, so it'd be a "nice to have" for HardenedBSD. We'd gain fully encrypted root support with no need for a nonencrypted /boot partition. Is this something we want to take on for HardenedBSD? PC-BSD has it.

**Comment by opntr** [comment]
Grub licensed under GPL.
