### ISSUE TITLE
Recursive setfacl Support

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD#99]
I once submitted a patch upstream to FreeBSD to add recursive support to setfacl. FreeBSD wanted me to rewrite the patch to clean it up a bit and make it less memory-intensive. The bug report has sat around for quite some time. I came up with a situation today where recursive setfacl would have been great to have. Rewrite the patch and upstream to FreeBSD.

Original FreeBSD bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=155163

**Comment by opntr** [comment]
Is the rewritten patch committed or the original?

**Comment by lattera** [comment]
This is the rewritten patch. I rewrote it to use the ftw(3) facility.

**Comment by opntr** [comment]
Than we should close this ticket?

**Comment by lattera** [comment]
Let me make a couple more commits. I forgot to update usage() and I need to update the manpage.
